### ISSUE TITLE
Net daemons becoming Zombies

### ISSUE THREAD

**Issue by Mellvik** [ghaerr/elks#1066]
Network daemon subprocesses frequently become permanent zombies upon exit – as evidenced by connecting to `elks` via `telnet` or `ftp` and then exit. 
Sometimes the zombies go away after a while, most of the time they don't. This (zombies going away after a while) seems to be the case more often with `telnetd` than with `ftpd`.

The main daemon process does not seem to be affected, they alway exit cleanly. 

I tried replacing `_exit()`with `exit()` in `ftpd`, but it does not seem to have made any difference.

```
# ps                                                                            
  PID   GRP  TTY USER STAT CSEG DSEG  HEAP   FREE   SIZE COMMAND                
    1     0      root    S 3240 33ef  3072   2004  12832 /bin/init 4            
   24    24    1 root    S 37f7 3992     0   1974  13120 /bin/getty /dev/tty1   
  160   160   S0 root    S 3f59 46fb  3410   4428  52400 -/bin/sash             
   26    26   S1 root    S 37f7 4e5f     0   1980  13136 /bin/getty /dev/ttyS1 3
8400                                                                            
   11    11      root    S 5134 6383   618  35150  74992 ktcp -b elks1 10.0.2.2 
255.255.255.0                                                                   
   14    14      root    S 5561 4c28     0   2004  15312 telnetd                
  256   160   S0 root    R 56e7 3562  1024   1190  13584 ps                     
   20    20      root    S 5ddc 58d0     0  11434  30800 ftpd                   
  102     0      root    Z    0    0                                            
  163     0      root    Z    0    0                                            
  238     0      root    Z    0    0                                            
  239     0      root    Z    0    0                                            
  243     0      root    Z    0    0                                            
# 
```
The net status seems fine:
```
# netstat                                                                       
----- Received ---------  ----- Sent -------------                              
TCP Packets        39639  TCP Packets        59102                              
TCP Dropped            0  TCP Retransmits        1                              
TCP Bad Checksum       0  TCP Retrans Memory     0                              
IP Packets         39642  IP Packets         59103                              
IP Bad Checksum        0  IP Bad Headers         0                              
ICMP Packets           0  ICMP Packets           0                              
SLIP Packets           0  SLIP Packets           0                              
ETH Packets        39690  ETH Packets        59151                              
ARP Reqs Sent          1  ARP Replies Rcvd       1                              
ARP Reqs Rcvd         47  ARP Replies Sent      47                              
ARP Cache Adds         1                                                        
                                                                                
 No        State    RTT lport        raddress  rport                            
-----------------------------------------------------                           
  1  ESTABLISHED 1000ms  3623         0.0.0.0      2                            
  2       LISTEN 1000ms    21         0.0.0.0      0                            
  3       LISTEN 1000ms    23         0.0.0.0      0      
```

**Comment by ghaerr** [comment]
> Network daemon subprocesses frequently become permanent zombies upon exit – as evidenced by connecting to elks via telnet or ftp and then exit.
Sometimes the zombies go away after a while, most of the time they don't.

All processes become daemons upon exit, regardless of whether exit or _exit is called. The reason for this is to save the exit return code for the parent process. The zombie will remain until the parent process calls `wait`. If the programmer has not included a `wait` call, then the zombies will remain forever, until the parent process terminates, in which case the parentless zombies (now called orphans) are supposed be collected by the `wait` call in the running `init` (process 1).

This is the theory, at least; it is not yet perfect in ELKS, but the primary cause seems to be the lack of proper `wait` cleanup in the forking applications.

> This (zombies going away after a while) seems to be the case more often with telnetd than with ftpd.

Take a quick look at inet/telnetd/telnetd.c for the `'waitpid(-1, NULL, WNOHANG);     /* reap previous accepts*/' line. This solved most of it's problems - it waits only for the previously-spawned accept-forked process, which usually means there's one extra hanging around. It is complicated by the fact that if you wait prior to when the child has exited, the main process will hang. (After all, the system call is named wait!!)

> The main daemon process does not seem to be affected, they alway exit cleanly.

Hopefully this will help.
