### ISSUE TITLE
Disk size reports wrong suffix

### ISSUE THREAD

**Issue by ConiKost** [ghaerr/elks#1088]
**Description**
It looks like, that the suffix for reported disks is somehow static.
My master disk has always ```Mb``` as suffix, while slave always show ```Gb```
The size seems be correct. Only suffix is wrong.

**Configuration**
- Version (commit or release): Git master
- Emulator or HW platform: NuXT

**How to reproduce ?**
- Does the problem always happen ? Yes
- List the steps to reproduce the problem: Install two disks.

**Raw data**
A) Master: 8GB CF, Slave: 128MB CF
```/dev/hda: 972 cylinders, 255 heads, 63 sectors = 7624.6 Mb``` (This is a 8GB CF)
```/dev/hdb: 993 cylinders, 8 heads, 32 sectors = 124.1 Gb``` (This is a 128MB CF)

B) Master: 128MB CF, Slave: 8GB CF
```/dev/hda: 993 cylinders, 8 heads, 32 sectors = 124.1 Mb``` (This is a 128MB CF)
```/dev/hdb: 972 cylinders, 255 heads, 63 sectors = 7624.6 Gb``` (This is a 8GB CF)

**Comment by ghaerr** [comment]
@ConiKost,

What program are you running, or exactly where/when is this size information displayed?

**Comment by ghaerr** [comment]
> What program are you running, or exactly where/when is this size information displayed?

Oops, never mind, found it. You're having unset CONFIG_SMALL_KERNEL is causing some code I hadn't noticed before. Fix coming.
