### ISSUE TITLE
Remove sash from sys install

### ISSUE THREAD

**Issue by toncho11** [ghaerr/elks#1138]
sash command is not part of the 360kb image?
It did not copied on my hdd.
So I propose removing it from the sys install script elkscmd/rootfs_template/bin/sys

**Comment by ghaerr** [comment]
Hello @toncho11,

> sash command is not part of the 360kb image?

I think it was removed due to lack of space a while back.

> So I propose removing it from the sys install script elkscmd/rootfs_template/bin/sys

Ok. Would you like to resubmit your PR on that, or shall I remove it, thank you for noticing and testing!

**Comment by toncho11** [comment]
I am having problems making the PR with GIT.
Please do it.
