### ISSUE TITLE
[question] alternative 16-bit compliler?

### ISSUE THREAD

**Issue by staalmannen** [ghaerr/elks#12]
ELKS currently depend on bcc for building. I was just wondering if it would be interesting to try with an alternative 16-bit compiler, like for example OpenWatcom

https://github.com/open-watcom/open-watcom-v2

If it not a completely stupid idea, I might have a go at it and try (I already got busybox to build for linux and win32 with Watcom). I have seen some wiki pages on watcom for OS development over at OSDev.

http://wiki.osdev.org/Watcom

**Comment by jbruchon** [comment]
This idea has been presented more than once. It would be a very good idea to look over the mailing list discussions on the subject. Juan Perez-Sanchez has managed to build a GCC for ia16 CPUs and build ELKS with it. Note that it still doesn't actually work though.
http://www.spinics.net/lists/linux-8086/
