### ISSUE TITLE
External numpad of the IBM PS/2 L40 SX is not working

### ISSUE THREAD

**Issue by eloydegen** [ghaerr/elks#1226]
The numpad for the L40SX does never work, even after rebooting, using the XMS disabled version from @ghaerr. It is connected to the PS/2 port. I don't know how this can be fixed.

![image](https://user-images.githubusercontent.com/3866292/158263599-49f1b348-ff5d-489a-9d85-6508c86d6682.png)

**Comment by ghaerr** [comment]
Hello @eloydegen,

That sure is a nice-looking original PS/2 you have there!! I never knew there was an external keypad offered for it either :)

The reason why the external keypad isn't working is that there isn't any code in ELKS that talks to the PS/2 port, as well as not having an external PS/2-compatible keyboard driver. 

This could all be added, but there is the problem of finding who will do it, and then of course, testing it. Could you do the programming for it? I'm not familiar with the PS/2 port, but I seem to remember seeing documentation for it around. We would also need documentation on the external keypad, and how to communicate with it.

Thank you!
