### ISSUE TITLE
Incomplete build instructions (where is the cross-compiler?)

### ISSUE THREAD

**Issue by sebras** [ghaerr/elks#1231]
The [wiki](https://github.com/jbruchon/elks/wiki/) has an item for "Toolchain" under "Builnding" which doesn't link anywhere, and "Building" itself links to a paragraph ending with "Full instructions are [here](https://github.com/jbruchon/elks/wiki/#Building)." linking back to itself. I'm having using this information to locate the necessary 8086 cross-compiler to build ELKS. Do you mind completing the build instructions? This is a small issue, but adding a link to compiler ought to be easy enough. :)

**Comment by ghaerr** [comment]
Hi @sebras,

It appears the Wiki has a bad link, I'll fix that. The main page has full build instructions, which point to [here](https://github.com/jbruchon/elks/blob/master/BUILD.md).

Thank you!

**Comment by sebras** [comment]
Ah, thank you!
