### ISSUE TITLE
Shell interrupt problem

### ISSUE THREAD

**Issue by Mellvik** [ghaerr/elks#125]
Hitting ^C at the shell prompt cause the message
_can't cd to ??oot/.profile_
where ?? are garbage chars and the actual file name will vary. Occasionally the message will be different, such as _'HOME not set'._
Hitting a second ^C terminates the shell.

[ Tested with physical 286/AT and virtualbox]

**Comment by mfld-fr** [comment]
Also saw "HOME not set" message recently on default configuration, when interrupting the `ls` command.

**Comment by mfld-fr** [comment]
Fixed by #217
