### ISSUE TITLE
xms: A20 was off

### ISSUE THREAD

**Issue by astrobleem** [ghaerr/elks#1267]
**Description**
- What is expected ?
Expecting elks to boot 
- What is observed ?
I have provided a screenshot but the last line we see is 
"xms: A20 was off"

the machine appears frozen
num lock does not function and caps lock does not funtion

**Configuration**
- Version (commit or release): 0.5.0 and 0.2  I am pretty sure I tried 0.4.0 images you had available also, I have not tried to build my own.
- 
- Emulator or HW platform:
Real Hardware, not emulated
Tandy 1000 EX
640k memory expansion/CF-IDE/Gotek Floppy emulator

**How to reproduce ?**
- Does the problem always happen ?
- yes
- List the steps to reproduce the problem.
download any ELKS v0.5.0 image and try to boot

**Raw data**
- Screenshot(s):
![image](https://user-images.githubusercontent.com/7433842/165656742-5b221fd1-5c18-456b-9259-fc4b1d0c8e89.png)

- Log file:

**Additional information**
Add any other context information about the problem here.

willing to help out in any way to provide extra info/debugging

**Comment by ghaerr** [comment]
Hello @astrobleem,

Thanks for the boot problem report. The ELKS v0.5.0 boot images were incorrectly configured to assume a machine with XMS capabilities, and when they're missing, the images fail to boot. A solution is to recompile the system with XMS turned off, but we provided a FAT-based boot image for a user with this same problem in #1199.

Take a look at that issue, or [download this link](https://github.com/jbruchon/elks/files/8173579/fd1440-fat.img.zip) to see if that image boots and solves your problem.

Thank you!

**Comment by astrobleem** [comment]
So sorry to create an issue when one already existed. For what it's worth I did make an attempt to look for a similar issue. 

I used the fd1440-fat.img.zip  you linked to, and encounter a new error

We see 

ELKS.3!
Press key


If I press a key the system reboots.

This loops over and over and over.

**Comment by astrobleem** [comment]
![image](https://user-images.githubusercontent.com/7433842/165783278-d8f94519-8fe6-436e-abea-87c387910442.png)

**Comment by ghaerr** [comment]
> ELKS.3!

The '3' means no /Linux in the root directory of the FAT (MSDOS) disk. Did you use 'dd' to copy it? Using MSDOS won't work.

What size drive are you using in the PC, 1440K drive?
Which v0.5.0 image did you use in your first test?

Thank you!

**Comment by ghaerr** [comment]
Chad,

I just compiled up a latest version on 1440K drive, MINIX image. Please see if this boots, thanks!
[fd1440.img.zip](https://github.com/jbruchon/elks/files/8584404/fd1440.img.zip)

**Comment by astrobleem** [comment]
![image](https://user-images.githubusercontent.com/7433842/165809853-aa4ca634-a652-4e99-9ca0-088f30a5de61.png)

fd360-fat.img
gets us to the A20 off message.


I am using a gotek floppy USB writing using USB Batch Manage Tool 1.4

![image](https://user-images.githubusercontent.com/7433842/165810962-ba5fd60c-2168-47ab-8a5f-fc950f4a8472.png)

....
testing with the 1.44 fat image from 0.5.0 gets ELKS.3!
![image](https://user-images.githubusercontent.com/7433842/165811852-d0996452-e1b4-4f59-af20-be7ccd58ee6d.png)

360 image gets me to a20, 
720 image gets me to a20,
1440 gets me elks.3

I guess this means that my system doesnt support 1.44m images.

**Comment by ghaerr** [comment]
> I guess this means that my system doesnt support 1.44m images.

Probably not, but that's ok. Here's a couple 360K images, FAT and MINIX. Try them out, they should work.
[fd360-minix.img.zip](https://github.com/jbruchon/elks/files/8585100/fd360-minix.img.zip)
[fd360-fat.img.zip](https://github.com/jbruchon/elks/files/8585102/fd360-fat.img.zip)

**Comment by astrobleem** [comment]
yeehaw!

![image](https://user-images.githubusercontent.com/7433842/165814251-24b41ac5-a283-49d4-ba94-867562eeccbe.png)

**Comment by ghaerr** [comment]
> yeehaw!

Well, glad we were able to solve that problem! It is as I suspected, the v0.5.0 images require XMS, sorry.

The 360k images don't have much on them, you might want to try configuring your GoTek to support 1.44M floppy, then use one of the 1440K images I sent you. If you want to try compiling everything from scratch, you can read the Build section of the Github README.

I may try to cut a new v0.5.1 with fixed images, as your problem did happen to another new user.

Thank you!

**Comment by astrobleem** [comment]
I hope it's not asking too much, could you hook me up with a hd mbr fat 32m  image ?

I have a compact flash drive.

**Comment by ghaerr** [comment]
Sure, here's the HD32 mbr and non-mbr images.
[hd32mbr-fat.img.zip](https://github.com/jbruchon/elks/files/8585178/hd32mbr-fat.img.zip)
[hd32-fat.img.zip](https://github.com/jbruchon/elks/files/8585179/hd32-fat.img.zip)

**Comment by astrobleem** [comment]
I'll test them out, 
Thank you so much.

Is it possible to detect the presence of XMS without having to compile this in?

**Comment by ghaerr** [comment]
> Is it possible to detect the presence of XMS without having to compile this in?

No, not on earlier (and all) machines, unfortunately. The next release will not have XMS compiled in, so this won't be an issue.

**Comment by astrobleem** [comment]
that booted up very fast!!

![image](https://user-images.githubusercontent.com/7433842/165816488-b5214ba0-4aac-49f7-a78f-1a5704a42cb3.png)
![image](https://user-images.githubusercontent.com/7433842/165816856-f5436033-facb-44c7-aea9-a995a421ddad.png)

**Comment by astrobleem** [comment]
this is awesome. thank you closing the issue.
