### ISSUE TITLE
MicroPython?

### ISSUE THREAD

**Issue by jedie** [ghaerr/elks#1277]
Will it ever be possible to get MicroPython running?!?

**Comment by ghaerr** [comment]
Hello @jedie,

Looking at https://micropython.org, it says that MicroPython can run in as little as 256K code and 16K RAM. ELKS can at best, using our current far model, only support 128K code, so it does not look possible at the moment. Also, I haven't looked at any of the source to see whether running on a 16-bit int machine will pose porting problems.

Thank you!

**Comment by cocus** [comment]
It seems to be quite modular though, so it should be possible to disable features until it fits. There's a unix port already, so it should be "easy" to port it. I see heavy usage of pointers with malloc/free, and no regards to the segmented memory model. There's a dsPIC33F variant (16 bit MCU) which although it might contain heaps of flash, it is indeed limited (and a 16 bit target). I had a glance at the config but I couldn't understand how to selectively enable or disable stuff so the binary size gets as small as possible.

**Comment by jedie** [comment]
> I couldn't understand how to selectively enable or disable stuff so the binary size gets as small as possible.

Maybe good starting point is the minimal port -> https://github.com/micropython/micropython/tree/master/ports/minimal

**Comment by ghaerr** [comment]
> Maybe good starting point is the minimal port -> https://github.com/micropython/micropython/tree/master/ports/minimal

It appears that "minimal" port still requires 32 bit CPU. The documentation does show a 16-bit PIC version: https://github.com/micropython/micropython/tree/master/ports/pic16bit.

I don't know Python well enough to take this on. Any takers? Contributions welcome and I'll help if possible.
