### ISSUE TITLE
ELKS 0.5.0 hangs up on boot XMS problem?

### ISSUE THREAD

**Issue by sergione78** [ghaerr/elks#1295]
Hello, i made a boot floppy for my commodore pc 10.
The boot seems to proceed well, but the pc hangs up on this message: xms: A20 was off
I thought there was an issue with the media, so I made another 5,25 boot disk using the other image, but nothing, same issue.
[
![IMG_0474](https://user-images.githubusercontent.com/74100799/168900452-317d7b12-a4da-4cdb-8054-439296b1f386.jpg)
](url)

Later I made another boot floppy for my toshiba t1200, and experienced the same issue

![IMG_0476](https://user-images.githubusercontent.com/74100799/168901172-203d2f74-92cf-4438-a2eb-176af411b775.jpg)

but this time the boot process went on by just pressing the enter key.  The XMS was disabled. 

my cpu is 8088
stock ati video card (mda, and perhaps hercules or cga emulation)
640 kb ram
2 x 5,25 floppy double density disk drive 

even though I don't have a lot of command line experience, I really appreciate EKLS.
My goal is to use linux to access my local network. With ms-dos typing a program in gwbasic I was able to transfer the interlink program with a null-modem cable and from this I was able to download other software, including the EKLS disk image.
Any suggestions?

**Comment by ghaerr** [comment]
Hi @sergione78,

The problem you are having is the same as #1267 - the ELKS v0.5.0 disks were incorrectly made with XMS support turned on, which doesn't work on a majority of older systems. You should be able to (re)download one of the latest builds [for instance here](https://github.com/jbruchon/elks/pull/1294/checks) under the "Artifacts" button on the upper right, which should work correctly.

Thank you!

**Comment by sergione78** [comment]
thank you very much! I'm sorry if I didn't notice before.

**Comment by Mellvik** [comment]
@ghaerr,

maybe it's time to eliminate this recurring problem by moving to 0.6.0 - thus enacting on our stated intentions after 0.5.0 to reduce the interval between releases.

—M
