### ISSUE TITLE
fail to compile elkscmd/ktcp/vjhc.c 

### ISSUE THREAD

**Issue by lynus** [ghaerr/elks#13]
Here is the output:
# bcc -ansi -O -0 -D__KERNEL__ -I/home/lynus/elks/elks/include -c -o vjhc.o vjhc.c

00427                                           if ip_vjhc_compress.off=0
****\* relocation impossible..............................................^
00438                                           if ip_vjhc_compress.off=0
****\* relocation impossible..............................................^
00469                                           if ip_vjhc_compress.off=0
****\* relocation impossible..............................................^

00003 errors
00000 warnings
../Make.defs:122: recipe for target 'vjhc.o' failed

**Comment by lynus** [comment]
It seems that it is the compiler to blame. The error raise when I use your dev86 toolchain.
But I installed bcc via `apt-get install bcc', the build success.

**Comment by jbruchon** [comment]
This was a problem with new `dev86` code I pulled in from upstream (see https://github.com/lkundrak/dev86/issues/11 for more info). I have reverted the commit that caused this error in my `dev86` tree as of commit jbruchon/dev86@4e8476e and tested against ELKS to ensure it works correctly.
