### ISSUE TITLE
Possible ktcp/SLIP bug

### ISSUE THREAD

**Issue by Mellvik** [ghaerr/elks#1368]
@ghaerr - I'm hoping you had an idea about this one:

I've been running `slip` a lot lately (not `cslip` which has issues, but that's a different story, to be revisited) and keep running into a problem that can be reproduced as follows:

- Boot system with `slip` as the default network setting
- ELKS comes up with `slip` active and working (in my case on `ttyS1`, console is on `ttyS0`, there is a `getty` running on `ttyS2`)
- Run `net stop`, `ps` confirms everything network related is gone
- Run `net start slip`
- The net starts like the first time and works, but all processes connected to `ttyS0` and `ttyS2` are gone and no new `getty` starts.
- Run (from either a telnet session or the physical console) `init 3`, and `getty`s restart on S0 and S2.

So it seems the second (and later) `net start` somehow affect `init` which needs a kick to get back amongst the living.

Ideas welcome.

```
Direct console, scan kbd 80x25 emulating ANSI (3 virtual consoles)
ttyS0 at 0x3f8, irq 4 is a 16550A
ttyS1 at 0x2f8, irq 3 is a 16550A
ttyS2 at 0x3e8, irq 10 is a 16550A
ttyS3 at 0x2e8, irq 7 is a 16550A
64 ext buffers, 65536 ram
eth: ne2k at 0x380, irq 9 (8bit), MAC 00:1f:11:02:60:2d, flags 0x80
eth: wd80x3 at 0x240, irq 2, ram 0xce00 not found
eth: 3c509 at 0x330, irq 11 not found
bioshd: hda BIOS CHS 992,16,63
bioshd: hda  IDE CHS 993,16,63
bioshd: hdb BIOS CHS 728,2,1
/dev/hda: 993 cylinders, 16 heads, 63 sectors = 488.7 Mb
/dev/hdb: 728 cylinders, 2 heads, 1 sectors = 728.0 kb
/dev/fd0: 80 cylinders, 2 heads, 18 sectors = 1440.0 kb
Partitions: hda:(0,1000944)  hda1:(63,696465)  hda2:(696528,132048)  hda3:(828576,132048)  hda4:(960624,41328) 
 hdb:(0,1456)  hdb1:(1,1455) 
device_setup: BIOS drive 0x80, root device 0x303
PC/AT class machine, syscaps 0xff, 608K base ram.
ELKS kernel 0.6.0 (56336 text, 11856 ftext, 8048 data, 42416 bss, 15070 heap)
Kernel text at d0:0000, ftext e91:0000, data 1176:0000, top 9800:0, 474K free
VFS: Mounted root 0x0303 (minix filesystem).
Running /etc/rc.sys script
fsck -ra /dev/hda3: /dev/hda3 is clean, no check.
Starting networking on slip
ktcp -b -p slip -s 38400 -l /dev/ttyS1 10.0.3.17 10.0.3.2 255.255.255.0
ktcp: ip 10.0.3.17, gateway 10.0.3.2, netmask 255.255.255.0
ktcp: slip /dev/ttyS1 baud 38400 mtu 1024
Starting daemons 'telnetd' 'ftpd -d' 
Tue Jul 12 18:55:14 2022


ELKS 0.6.0

login: root
elks17# net stop
Stopping network
elks17# ps
  PID   GRP  TTY USER STAT CPU  HEAP  FREE   SIZE COMMAND
    1     0      root    S   0  3072  2008  13008 /bin/init 3 
   17    17    1 root    S   0     0  1978   8656 /bin/getty /dev/tty1 
   18    18   S0 root    S   0  1188 13186  68816 -/bin/sh 
   19    19   S2 root    S   0     0  1968   8656 /bin/getty /dev/ttyS2 57600 
   26    18   S0 root    R   6  1024  1182  11792 ps 
elks17# net start slip
Starting networking on slip
ktcp -b -p slip -s 38400 -l /dev/ttyS1 10.0.3.17 10.0.3.2 255.255.255.0
ktcp: ip 10.0.3.17, gateway 10.0.3.2, netmask 255.255.255.0
ktcp: slip /dev/ttyS1 baud 38400 mtu 1024
Starting daemons 'telnetd' 'ftpd -d' 
elks17#                      <---------------------- at this point the terminal goes dead, a network login confirms there is no process assigned to this line (ttyS0)
<------------------------- 'init 3' is entered from a network login

ELKS 0.6.0

login: 
login: root
elks17# cat /bootopts
## boot options max 511 bytes
console=ttyS0,57600  net=slip 3 # sercons, multiuser, networking
#QEMU=1			# to use ftp/ftpd in qemu
#TZ=MDT7
LOCALIP=10.0.3.17
HOSTNAME=elks17
ne2k=9,0x380,,0x80
#wd8003=2,0x280,0xCE00,0x80
3c509=11,0x330,,0x80
#bufs=500		# system buffers
#sync=30		# autosync secs
#init=/bin/init 3 n	# multiuser serial no /etc/rc.sys
#init=/bin/sh		# singleuser shell
#root=hda2 		# root hd partition 1, read-only
#console=ttyS0,19200 3	# serial console
elks17# net stop                      <------------ next round
Stopping network
elks17# ps
  PID   GRP  TTY USER STAT CPU  HEAP  FREE   SIZE COMMAND
    1     0      root    S   0  3072  2008  13008 /bin/init 3 
   17    17    1 root    S   0     0  1978   8656 /bin/getty /dev/tty1 
   55    39   S0 root    R   0  1024  1182  11792 ps 
   39    39   S0 root    S   0  1188 13186  68816 -/bin/sh 
   40    40   S2 root    S   0     0  1968   8656 /bin/getty /dev/ttyS2 57600 
elks17# net start slip
Starting networking on slip
ktcp -b -p slip -s 38400 -l /dev/ttyS1 10.0.3.17 10.0.3.2 255.255.255.0
ktcp: ip 10.0.3.17, gateway 10.0.3.2, netmask 255.255.255.0
ktcp: slip /dev/ttyS1 baud 38400 mtu 1024
Starting daemons 'telnetd' 'ftpd -d' 
elks17#           <-------- line goes dead again.
```

**Comment by ghaerr** [comment]
Hello @Mellvik,

We need to see what /bin/init is doing, can you "define DEBUG 1" in elkscmd/sys_utils/init.c? That will report exactly what its doing to the console. We want to see whether the net start or stop commands cause init to cancel any running getty processes.

A warning: init can act very strangely immediately after boot; it has code that prevents restarting getty/login if the process terminates before 4 seconds has elapsed. In order to see this, boot ELKS (on QEMU) and type ^D at the login prompt immediately. The login will exit and the system appears hung, but actually its just init not restarting the login.

Thank you!

**Comment by Mellvik** [comment]
OK @ghaerr,

here's the whole shebang… I'm sure you can make some sense of it …

-M

Direct console, scan kbd 80x25 emulating ANSI (3 virtual consoles)
ttyS0 at 0x3f8, irq 4 is a 16550A
ttyS1 at 0x2f8, irq 3 is a 16550A
ttyS2 at 0x3e8, irq 10 is a 16550A
ttyS3 at 0x2e8, irq 7 is a 16550A
64 ext buffers, 65536 ram
eth: ne2k at 0x380, irq 9 (8bit), MAC 00:1f:11:02:60:2d, flags 0x80
eth: wd80x3 at 0x240, irq 2, ram 0xce00 not found
eth: 3c509 at 0x330, irq 11 not found
bioshd: hda BIOS CHS 992,16,63
bioshd: hda  IDE CHS 993,16,63
bioshd: hdb BIOS CHS 728,2,1
/dev/hda: 993 cylinders, 16 heads, 63 sectors = 488.7 Mb
/dev/hdb: 728 cylinders, 2 heads, 1 sectors = 728.0 kb
/dev/fd0: 80 cylinders, 2 heads, 18 sectors = 1440.0 kb
Partitions: hda:(0,1000944)  hda1:(63,696465)  hda2:(696528,132048)  hda3:(828576,132048)  hda4:(960624,41328) 
 hdb:(0,1456)  hdb1:(1,1455) 
device_setup: BIOS drive 0x80, root device 0x303
PC/AT class machine, syscaps 0xff, 608K base ram.
ELKS kernel 0.6.0 (56336 text, 11856 ftext, 8048 data, 42416 bss, 15070 heap)
Kernel text at d0:0000, ftext e91:0000, data 1176:0000, top 9800:0, 474K free
VFS: Mounted root 0x0303 (minix filesystem).
/bin/init: starting
ARGS: '/bin/init''3'
ENV: 'net=slip''LOCALIP=10.0.3.17''HOSTNAME=elks17''ROOTDEV=/dev/hda3'
/bin/init: SCAN sysinit
/bin/init: spawning 2 '/etc/rc.sys'
/bin/init: execv '/bin/sh' '-c' '/etc/rc.sys'
Running /etc/rc.sys script
fsck -ra /dev/hda3: /dev/hda3 is clean, no check.
Starting networking on slip
init: starting
ARGS: 'init''1'
ENV: 'HOSTNAME=elks17''LOCALIP=10.0.3.17''net=slip''PATH=/bin''ROOTDEV=/dev/hda3'
init: change to runlevel 1
/bin/init: ktcp -b -p slip -s 38400 -l /dev/ttyS1 10.0.3.17 10.0.3.2 255.255.255.0
signaled 1
ktcp: ip 10.0.3.17, gateway 10.0.3.2, netmask 255.255.255.0
/bin/init: ktcp: slip /dev/ttyS1 baud 38400 mtu 1024
previous runlevel Starting daemons 1, new runlevel 'telnetd' 1
'ftpd -d' 
Tue Jul 12 20:45:04 2022
/bin/init: SCAN start runlevel 3
/bin/init: ENTERUNLVL id:1:initdefault: /bin/init: ENTERUNLVL si::sysinit:/etc/rc.sys discarded
/bin/init: ENTERUNLVL t1:1356:respawn:/bin/getty /dev/tty1 
/bin/init: spawning 17 '/bin/getty /dev/tty1'
/bin/init: ENTERUNLVL t2:56:respawn:/bin/getty /dev/tty2 /bin/init: ENTERUNLVL t3:56:respawn:/bin/getty /dev/tty3 /bin/init: ENTERUNLVL s0:2346:respawn:/bin/getty /dev/ttyS0 57600 
/bin/init: spawning 18 '/bin/getty /dev/ttyS0 57600'
/bin/init: ENTERUNLVL s2:346:respawn:/bin/getty /dev/ttyS2 57600 
/bin/init: spawning 19 '/bin/getty /dev/ttyS2 57600'
/bin/init: execv '/bin/getty' '/dev/tty1' '(null)'
/bin/init: execv '/bin/getty' '/dev/ttyS0' '57600'


ELKS 0.6.0

login: /bin/init: execv '/bin/getty' '/dev/ttyS2' '57600'

login: root
elks17# net stop
Stopping network
/bin/init: wait child exit 11
/bin/init: wait child exit 13
elks17# /bin/init: wait child exit 15
net start slip          <——— THIS is the net start that causes trouble -----------------------
Starting networking on slip
init: starting
ARGS: 'init''1'
ENV: 'USER=root''HOSTNAME=elks17''HOME=/root''LOCALIP=10.0.3.17''TERM=ansi''PATH=/bin''ROOTDEV=/dev/hda3''SHELL=/bin/sh'
init: change to runlevel 1
/bin/init: ktcp -b -p slip -s 38400 -l /dev/ttyS1 10.0.3.17 10.0.3.2 255.255.255.0
signaled 1
ktcp: ip 10.0.3.17, gateway 10.0.3.2, netmask 255.255.255.0
/bin/init: ktcp: slip /dev/ttyS1 baud 38400 mtu 1024
previous runlevel Starting daemons 3, new runlevel 1
'telnetd' /bin/init: SCAN exitrunlevel
/bin/init: 'ftpd -d' EXITRUNLVL id:1:initdefault: 
elks17# 
/bin/init: EXITRUNLVL si::sysinit:/etc/rc.sys 
/bin/init: EXITRUNLVL t1:1356:respawn:/bin/getty /dev/tty1 
/bin/init: EXITRUNLVL t2:56:respawn:/bin/getty /dev/tty2 stop not running
/bin/init: EXITRUNLVL t3:56:respawn:/bin/getty /dev/tty3 stop not running
/bin/init: EXITRUNLVL s0:2346:respawn:/bin/getty /dev/ttyS0 57600 stop 
/bin/init: EXITRUNLVL s2:346:respawn:/bin/getty /dev/ttyS2 57600 stop 
/bin/init: SCAN start runlevel 1
/bin/init: ENTERUNLVL id:1:initdefault: discarded
/bin/init: ENTERUNLVL si::sysinit:/etc/rc.sys discarded
/bin/init: ENTERUNLVL t1:1356:respawn:/bin/getty /dev/tty1 already running
/bin/init: ENTERUNLVL t2:56:respawn:/bin/getty /dev/tty2 /bin/init: ENTERUNLVL t3:56:respawn:/bin/getty /dev/tty3 /bin/init: ENTERUNLVL s0:2346:respawn:/bin/getty /dev/ttyS0 57600 /bin/init: ENTERUNLVL s2:346:respawn:/bin/getty /dev/ttyS2 57600 /bin/init: wait child exit -1
/bin/init: wait child exit 18
/bin/init: wait child exit 19

**Comment by ghaerr** [comment]
> net start slip          <——— THIS is the net start that causes trouble -----------------------
Starting networking on slip
init: starting
ARGS: 'init''1'
ENV: 'USER=root''HOSTNAME=elks17''HOME=/root''LOCALIP=10.0.3.17''TERM=ansi''PATH=/bin''ROOTDEV=/dev/hda3''SHELL=/bin/sh'
init: change to runlevel 1

@Mellvik:  `net start slip` is running `init 1` to turn off any getty's running:
```
getty_off()
{
    # turn off any serial gettys running
    init 1
}
```
Looks like that needs to be changed. I think I put that in there just in case SLIP was configured to use one of the active getty lines. Go ahead and comment that out, and look at the script a bit and see what you think we should do. We could go back to multiuser mode, but we don't know the previous mode. Ideas welcomed.

**Comment by Mellvik** [comment]
> 
> ﻿
> net start slip <——— THIS is the net start that causes trouble -----------------------
> Starting networking on slip
> init: starting
> ARGS: 'init''1'
> ENV: 'USER=root''HOSTNAME=elks17''HOME=/root''LOCALIP=10.0.3.17''TERM=ansi''PATH=/bin''ROOTDEV=/dev/hda3''SHELL=/bin/sh'
> init: change to runlevel 1
> 
> @Mellvik: net start slip is running init 1 to turn off any getty's running:
> 
> getty_off()
> {
>     # turn off any serial gettys running
>     init 1
> }
> Looks like that needs to be changed. I think I put that in there just in case SLIP was configured to use one of the active getty lines. Go ahead and comment that out, and look at the script a bit and see what you think we should do. We could go back to multiuser mode, but we don't know the previous mode. Ideas welcomed.
> 

Aaah, I see. Yes we do need to change that. The easy way out would be to request an exclusive open on the device and fail if we cannot get it. I suspect that's not supported (yet).
Going with  ps and grep doesn't cut it since init will restart any getty anyway. How about having an option to init telling it to stop and block processes on a given port until further notice?

The first is the cleanest (and most common I think).

Thank you.


-M

**Comment by ghaerr** [comment]
> The easy way out would be to request an exclusive open on the device and fail if we cannot get it. 

That's a good idea.

> I suspect that's not supported (yet).

Correct, it currently allows multiple opens, which is required for `stty` to work.

> Going with  ps and grep doesn't cut it since init will restart any getty anyway.

Yep. ps and grep are only used for the required portions of net stop, to kill ktcp and its daemons.

I've added exclusive open to my TODO list, and will complete that shortly, along with moving the request_irq out of init into
rs_open.

In the meantime, let us know how `net start slip` works with `init 1` commented out.

**Comment by Mellvik** [comment]
Great, @ghaerr.

> 
> 
> The easy way out would be to request an exclusive open on the device and fail if we cannot get it.
> 
> That's a good idea.
> 
> I suspect that's not supported (yet).
> 
> Correct, it currently allows multiple opens, which is required for stty to work.
> 
Having an open(O with O_EXCL would of course be elegant, but I guess adding an IOCTL would be far easier, just returning BUSY if usecount >0 and set a flag to block more opens if not.
> 
> In the meantime, let us know how net start slip works with init 1 commented out.
> 
> 

Works great for me!

Thank you.

-M

**Comment by Mellvik** [comment]
It seems I forgot to respond to this one. 

Commenting out the `init 1`  line works fine for me. 
Maybe we should just leave it at that and assume the user is smart enough to not have a `getty` going on the slip line.

-M

**Comment by ghaerr** [comment]
> Commenting out the init 1 line works fine for me.
Maybe we should just leave it at that

Ok - I will remove the `init 1` in the next PR (I have a number in the works). I have also noted the idea of using O_EXCL as another possible solution, which I will look further into.

If that works, go ahead and close this issue and lets keep moving forward with the other open issues.
