### ISSUE TITLE
Compress executable missing on Debian/Ubuntu builds

### ISSUE THREAD

**Issue by sparky4** [ghaerr/elks#1372]
cant build on Debian 11
- What is expected ?
it is supposed to build
- What is observed ?
compress program not found

**Configuration**
- Version (commit or release):
current

**How to reproduce ?**
- Does the problem always happen ?
yes
- List the steps to reproduce the problem.
run ./build.sh

**Additional information**
```
ifdef CONFIG_APP_MAN_PAGES
        mkdir -p $(DESTDIR)/lib/man1
#       cp -rp man/man1 $(DESTDIR)/lib; compress -b 12 $(DESTDIR)/lib/man1/*
        mkdir -p $(DESTDIR)/lib/man2
#       cp -rp man/man2 $(DESTDIR)/lib; compress -b 12 $(DESTDIR)/lib/man2/*
        mkdir -p $(DESTDIR)/lib/man5
#       cp -rp man/man5 $(DESTDIR)/lib; compress -b 12 $(DESTDIR)/lib/man5/*
        mkdir -p $(DESTDIR)/lib/man7
#       cp -rp man/man7 $(DESTDIR)/lib; compress -b 12 $(DESTDIR)/lib/man7/*
        mkdir -p $(DESTDIR)/lib/man8
#       cp -rp man/man8 $(DESTDIR)/lib; compress -b 12 $(DESTDIR)/lib/man8/*
endif
```
i commented out the man pages stuff and it compiled! <3

**Comment by toncho11** [comment]
Yes, I had the same problem. I had to install "ncompress" on Ubuntu.

**Comment by ghaerr** [comment]
> Yes, I had the same problem. I had to install "ncompress" on Ubuntu.

Super @toncho11, that's definitely the problem and fix here, thanks!

@sparky4, we have a couple options here: since the actual problem is that the `compress` executable apparently isn't installed by default on Ubuntu or Debian 11, we can either 1) issue a helpful error message and stop the build, or 2) not compress the man pages, which will result in a much larger disk image (and the user won't know).

Any thoughts about the best way to proceed?

**Comment by toncho11** [comment]
I think you can update: https://github.com/jbruchon/elks/blob/master/BUILD.md , section "Prerequisites" - you can add that compress is also needed and explain that on Ubuntu and Debian (not sure) the package name is "ncompress".

**Comment by toncho11** [comment]
Actually on ubuntu you also need to do:
`sudo apt install build-essential` to install the C compiler, but everyone is supposed to know that.

**Comment by ghaerr** [comment]
> I think you can update: https://github.com/jbruchon/elks/blob/master/BUILD.md , section "Prerequisites" - you can add that compress is also needed

That's a good idea - and I can change the build so that it won't fail, but that man pages won't be compressed, so its actually optional.

> explain that on Ubuntu the package name is "ncompress".

So `sudo apt install ncompress` solves the problem on Ubuntu?

**Comment by toncho11** [comment]
`"apt-get"`

`sudo apt-get  install ncompress`

**Comment by ghaerr** [comment]
Hello @sparky4,

I've fixed this issue in #1372, please test and close this issue if it works for you.

Thank you!

**Comment by sparky4** [comment]
okay i will test!

**Comment by sparky4** [comment]
hey it works! thanks! :D
