### ISSUE TITLE
[fm] Change color of directories

### ISSUE THREAD

**Issue by toncho11** [ghaerr/elks#1420]
Please change the color of the directories in fm. Currently it is dark blue on black - very hard to read.

**Comment by ghaerr** [comment]
Agreed, will change to light blue for the console - I had seen this on QEMU but thought it was perhaps just QEMU. Good to know darker blue (which is supposed to be regular blue) is accurate on QEMU.

**Comment by toncho11** [comment]
Actually I am testing on emulator for now.

**Comment by ghaerr** [comment]
Changed as requested in #1427, thank you!
