### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by eloydegen** [ghaerr/elks#1441]
Hi,

Maybe I am looking at the wrong places, but I could not find what the minimum amount of required RAM is for ELKS. I have an IBM Portable Personal Computer with 512KiB RAM and don't know if that's a recommended amount for ELKS. I don't have a 5.25" floppy drive yet, so I can't test it yet on that machine.

**Comment by ATroubleshooter** [comment]
512k is good enough to run ELKS. As far as I remember, someone here tried and ran it on 256k, although in a somewhat limited configuration.

**Comment by eloydegen** [comment]
@ATroubleshooter Thank you! I'll keep this issue open because I'd like to hear some input on whether this should be listed in the README.

**Comment by Mellvik** [comment]
Thank you @eloy,

I agree with you. We should add something like 'minimum system requirements' to the beginning of the README.

—M

**Comment by eloydegen** [comment]
@Mellvik Nice! Would it make sense to distinguish between 'required' and 'recommended' RAM? Assuming the standard release binaries, no custom configurations. Any other system requirements apart from the RAM? Since PC-98 is supported, IBM PC compatibility is not required, but exceptions have to be explicitly supported I assume.

**Comment by ghaerr** [comment]
> Would it make sense to distinguish between 'required' and 'recommended' RAM? 

The "system requirements" for ELKS vary greatly, depending on the platform and programs configured to run during boot. For instance ELKS can run on a ROM-based 8018X SBC with 128k RAM, while a PC version with no networking running /etc/init, the ASH shell and /etc/rc.sys likely requires just 256k. Add networking with the local daemons running and you'd want 512k minimum. I'd suggest perhaps describing the memory requirements of each of ELKS components instead.

That said, a goal of this project is to boot up from any (ancient) PC-compatible system with 256K RAM or more (including the still-unsolved boot problems for the PCs in #1327). However, the stock images and /etc/rc.sys programs may require more, or a specialized configuration. Some testing should show real requirements for stock images.

Thank you!

**Comment by NathanGibbs3** [comment]
Maybe add an entry to the Wiki as well.

**Comment by eloydegen** [comment]
Thanks for the clear answer, I will try to do some tests in the coming days.

**Comment by Mellvik** [comment]
OK, let's rewind to the original issue: Systems requirements in the README.

IMHO we really need that. It's something a more or less random visitor will be looking for - 'can ELKS possibly run on my system?'

And while it - like @ghaerr points out - isn't easy (or possible) to be specific, we can paint the big picture in a few sentences or bullet-points.

The RFEADME starts by introducing the architecture(s) ELKS will run on, the next paragraph should be about requirements, such as 

- ELKS will run on any PC-compatible system with a floppy drive
- ELKS requires 256k RAM to run, 512k to be really useful 
- ELKS will boot and run from a 360k image, but with a very limited set of tools
- ROM-based systems can run in 128k RAM
- If a system runs DOS it will most likely run ELKS
- If DOS fails to boot, booting ELKS is a fast way to figure out what's wrong, using the detailed boot messages.
- Stock images require 512k RAM, PC console/keyboard and floppy

My 2cents.

-M

**Comment by toncho11** [comment]
Thank you @Mellvik.
But I think "ELKS requires 256k RAM to run, 512k to be really useful" needs more clarification to avoid confusion:
* A custom produced image, not provided in the download section, can boot with 256 KB of memory 
* ELKS requires 512 KB to be really useful
