### ISSUE TITLE
Unable to create comb360 

### ISSUE THREAD

**Issue by sparky4** [ghaerr/elks#15]
There is an issue with there being no free disk space.... ><

**Comment by jbruchon** [comment]
The `comb360` image builds with the default kernel configuration. If you add features which enlarge the kernel beyond the default configuration, it will not build `comb360` properly. I just removed the `swapon` command in commit df63010eb6b2b05928349c0cdc6be480a394d6e9 which seems unnecessary for a full 360K combined floppy image anyway and frees up about 7-8K of additional space. Kernel images larger than about 64K will not fit on that image without discarding important programs such as `vi`.

**Comment by sparky4** [comment]
ah ok thank you
