### ISSUE TITLE
login, add more apps

### ISSUE THREAD

**Issue by FreeLANMan** [ghaerr/elks#1556]
Hello, interesting project.
- What is the username and password for the images?
- Can I add new Linux programs just by compiling them with the indicated tool?
I was interested in the system because it works with the PCEmulator for the TTGO VGA32 board.

**Comment by ghaerr** [comment]
Hello @FreeLANMan,

> What is the username and password for the images?

You can login using `root` with no password.

> Can I add new Linux programs just by compiling them with the indicated tool?

Yes, please refer to some of the programs distributed with ELKS, they live under the elksmd/ directories, and their Makefiles will show easy ways to build them.

Thank you!

**Comment by toncho11** [comment]
Yes, there is documentation on how to cross compile a program. This is just to give you an idea:

`$ ./cross/bin/ia16-elf-gcc tinyedit.c -o tinyedit -melks -mcmodel=small` will use the 16 bit gcc compiler that compiles ELKS to compile the `tinyedit.c` file. Then you need to insert this file in a bootable image (mount the image and copy the file to it). Or copy the file to your existing ELKS installation. There is also maybe another option to run it with `blink16`.

Yes, I am also excited about running ELKS on a micro-controller!!! It is probably the least power hungry Linux available. You can for example put an esp32/Emulator/ELKS on a flying balloon :)  and then (if there is communication) log in to your balloon satellite.

**Comment by FreeLANMan** [comment]
Thanks for the answers. 
All fat disks have the same content?

**Comment by ghaerr** [comment]
> All fat disks have the same content?

Each FAT disk has the same content as the MINIX disk of the same size. As the image size gets larger from 360k, the same additional programs are added to FAT and MINIX disks. We recommend that you use an 1440k if possible.
