### ISSUE TITLE
full3 image crashes on boot

### ISSUE THREAD

**Issue by deephooloovoo** [ghaerr/elks#16]
I was trying to compile elks and get networking running with the full3 image, but I was not able to crash because there was an error about a double free which crashed completely. I narrowed down the issue to elks/arch/i86/mm/malloc.c in commit 4786296011e318ca250ad096ce3ccd4ae01b21fe

I am not familiar enough with the internals of malloc to fix the problem myself, as some of the optimizations look like they could be helpful when specific conditions are met.

**Comment by jbruchon** [comment]
Is this happening on real hardware or in an emulator?

**Comment by deephooloovoo** [comment]
It's happening on hardware, both a really old 286 and an also pretty old P3 laptop. I haven't been testing on an emulator.

**Comment by lithoxs** [comment]
It is a bug in malloc.c inadvertently introduced by me 2 commits ago. I already set a pull request that fixes this problem.

**Comment by jbruchon** [comment]
Fixed in commit 7ae683f0aefcbe8cf4fd75d69f6e7a8988e2d128
