### ISSUE TITLE
ELKS repo transferred to ghaerr

### ISSUE THREAD

**Issue by ghaerr** [ghaerr/elks#1663]
Hello all,

@jbruchon is moving off of GitHub and has transferred the ELKS repository over to @ghaerr. While nothing needs to be done for developers or users as the URLs are automatically being redirected, it is recommended that those with local forks change their `upstream` repository location to the new URL to avoid possible confusion. To do this, run:
```
git remote set-url upstream https://github.com/ghaerr/elks.git
```

There are no other changes being made.

Thank you!

**Comment by jbruchon** [comment]
🔥
