### ISSUE TITLE
8018X system: bell-8254.c:24:14: error: ‘SPEAKER_PORT’ undeclared

### ISSUE THREAD

**Issue by anchorz** [ghaerr/elks#1764]
make for 8018x system breaks in:

In file included from bell-8254.c:12:0:
bell-8254.c: In function ‘soundp’:
bell-8254.c:24:14: error: ‘SPEAKER_PORT’ undeclared (first use in this function)
     outb(inb(SPEAKER_PORT) | 0x03, SPEAKER_PORT);

not sure if the make rule is correct or not:
./elks/arch/i86/drivers/char/Makefile 

ifdef CONFIG_CONSOLE_DIRECT
OBJS += console-direct.o bell-8254.o
endif
endif

**Comment by ghaerr** [comment]
The reason this fails is that the Direct Console (that is, direct access to video RAM via CGA/EGA mode in IBM PCs) isn't supported in the 8018x build. The 8018x port uses the headless console (CONFIG_CONSOLE_HEADLESS).

Are you building this for a 8018X-based system that requires support for IBM PC-style text video modes?

**Comment by anchorz** [comment]
I just select the generic 8018x system. 

may be i am doing something wrong. selecting system 8018x in make menuconfig, does not allow any additional settings besides INTx and RTC.

**Comment by ghaerr** [comment]
> selecting system 8018x in make menuconfig, does not allow any additional settings besides INTx and RTC.

Thanks, I'll take a look at this. The 8018X port doesn't allow much configuration, but selecting it should not cause a compilation error.
