### ISSUE TITLE
Incompatibility with 3inONEder

### ISSUE THREAD

**Issue by cathoderaydude** [ghaerr/elks#1772]
I recently obtained a device called a "3inONEder", which is a combo XTIDE, sound card, and NE2000 NIC for Toshiba's extremely early PC laptops, and found that it disrupts the ELKS boot process in profound ways. I should note that I'm testing with the same Toshiba T1100+ that had boot issues with the current release version of ELKS, which we resolved in #1692. I have tested with the latest version in that thread (ending -4) and also the one from #1694 (ending -3) and had the same results.

First, here it is working, with the 3inONEder card removed, just the base T1100+ laptop:

![image](https://github.com/ghaerr/elks/assets/46694173/dce3d8a8-5434-450d-9af9-c5a933cf1a68)

Next, I plug the card in, with a CF card in the slot, and the below happens:

![image](https://github.com/ghaerr/elks/assets/46694173/6144b765-c439-443a-94f9-ac5df5b648aa)

I should note that I can read this card if I boot from a DOS floppy, and in fact I fdisked, formatted, and sys'ed it from a DOS 3.3 disk, but the machine hangs if I try to boot from it. So, it's possible the card itself is corrupted in some way, and that may be a separate problem, but it seems like an unreadable FS on a secondary storage device shouldn't hang ELKS. Additionally, I don't even see an indication that it detected the HDD, there's no mention of e.g. /dev/hda, so I suspect this has nothing to do with the contents of the CF card itself.

Next, I remove the CF card and attempt to boot again. The following sequence occurs:

![image](https://github.com/ghaerr/elks/assets/46694173/a45bf209-69c4-4fbb-ad9b-c3c7a3004ce5)

![image](https://github.com/ghaerr/elks/assets/46694173/8c894421-8300-433c-94ea-3376652b0122)

This is using the minix version. If I use FAT, it gets about this far, but just keeps reporting continuously incrementing track read retries until I power it off.

I found one other issue, #1094, reporting failures with using a 3inONEder, but it's on a T1200 and also using the CF card exclusively, so I don't know how relevant that is. And frankly, given that this is a one-off custom peripheral for a specific and ancient machine, I will totally understand if it's a WONTFIX situation, since I have no idea how you'd debug this.

Happy to help from my end of course, but for all we know the card is defective and simply spitting noise onto the system bus; it's entirely possible, given that this is a handbuilt hobbyist device. I figured I would report it anyway though and see if anything stands out from the logs.

Thanks!

**Comment by cathoderaydude** [comment]
Sorry, I had originally titled it after the XTIDE since that seemed like the most likely culprit, before I checked and found other people seem to be using XTIDEs with no trouble.

**Comment by ghaerr** [comment]
Hello @cathoderaydude,

IIRC, @vutshi had issues very similar to this when running on an ancient (Russian or German?) machine with an XTIDE BIOS. I will have to look in the closed issues to find it, it was sometime during the summer. The issue(s) were finally resolved after replacing the CF card multiple times until one that finally worked with XTIDE was found, for unknown reasons! The errors turned out to have nothing to do with ELKS, per se.

In general, I think the ELKS BIOS floppy and hard disk driver(s) are working quite well, and unlikely to have bug(s) of this magnitude.

Thank you!

**Comment by ghaerr** [comment]
[Here's the issue](https://github.com/ghaerr/elks/issues/1619) https://github.com/ghaerr/elks/issues/1619.
