### ISSUE TITLE
ELKs rebuilds with no configuration changes

### ISSUE THREAD

**Issue by djohanse** [ghaerr/elks#1787]
**Description**
- What is expected
- Pull of elks source code from git repo.  Build using build.sh.  After image is successfully built, run build.sh again to get config menu.  Select exit, then select do not save changes.  I would not expect make to run at this point since nothing changed.
- 
- What is observed ?
- Make is run to recreate the image.  This takes a few minutes.  If I just want to see the config options but not change anything I would not expect to wait for a new build.

**Configuration**
- Version. 0.8.0 (from Qemu startup while running freshly built fd1440.img
- Emulator or HW platform:

**How to reproduce ?**
- Does the problem always happen ? Yes
- List the steps to reproduce the problem.
Described above

**Raw data**
- Screenshot(s):
- Log file:

**Additional information**
Add any other context information about the problem here.

**Comment by ghaerr** [comment]
Thanks for pointing this out. Although the ELKS build instructions do indicate to use `./build.sh`, that shell script is now used and tested only for the Github Continuous Integration, to check PRs before commit. I'll update the build instructions to suggest using the following:
```
make menuconfig
make                         # to build C library, kernel and applications
cd images; make images       # to build all floppy and HD images
```
