### ISSUE TITLE
Net start does not start httpd

### ISSUE THREAD

**Issue by djohanse** [ghaerr/elks#1789]
Followed directions in README.md for starting networking in QEMU.  Elks image was built with ne2k adapter.  Elks version 0.8.0-dev.  Downloaded via GitHub and built from source.

After logging in and running net start:

Attempting to connect via http://localhost:8080 doesn't work.

netstat shows ports 21, 23 and 1024 open.

When I run httpd from the elks command line that seems to fix the issue.  netstat then shows port 80 open and http://localhost:8080 successfully connects to elks server

Side note: may want to change text in link of server.  I think jbruchon is no longer correct.

Current text:

If you can see this page the web server worked.
Visit https://github.com/jbruchon/elks

**Comment by ghaerr** [comment]
Since ELKS is currently limited to a maximum of 16 processes, `httpd` is not automatically started with `net start`. If you want it, edit the `netstart=` line in /etc/net.cfg to read `netstart="telnetd ftpd httpd"`.

> Side note: may want to change text in link of server. I think jbruchon is no longer correct.

Thanks! Will update.
