### ISSUE TITLE
build.sh fails. pushd is not found

### ISSUE THREAD

**Issue by sparky4** [ghaerr/elks#192]
[12:43:40][~/p/elks]
[sparky4@lappy4]$ sudo ./build.sh 
-e 
WARNING: Disk images can only be built if you have root permissions
./build.sh: 38: ./build.sh: pushd: not found
./build.sh: 39: .: Can't open ./env.sh

**Comment by sparky4** [comment]
also

bcc -s -ansi -o ash builtins.o cd.o dirent.o error.o eval.o exec.o expand.o input.o jobs.o mail.o main.o memalloc.o miscbltin.o mystring.o nodes.o options.o parser.o redir.o show.o signames.o syntax.o trap.o output.o var.o init.o bltin/echo.o bltin/expr.o bltin/regexp.o bltin/operators.o
make[2]: Leaving directory '/home/sparky4/p/elks/elkscmd/ash'
make[2]: Entering directory '/home/sparky4/p/elks/elkscmd/bc'
flex -I -8 scan.l
make[2]: flex: Command not found
Makefile:80: recipe for target 'scan.c' failed
make[2]: *** [scan.c] Error 127
make[2]: Leaving directory '/home/sparky4/p/elks/elkscmd/bc'
Makefile:52: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/sparky4/p/elks/elkscmd'
Make.defs:192: recipe for target 'me' failed
make: *** [me] Error 2


when i try to make in elkscmd

**Comment by sparky4** [comment]
i changed
#!/bin/sh
to
#!/bin/bash

and it fixed it!

**Comment by sparky4** [comment]
flex -I -8 scan.l
make[2]: flex: Command not found
Makefile:80: recipe for target 'scan.c' failed
make[2]: *** [scan.c] Error 127
make[2]: Leaving directory '/home/sparky4/p/elks/elkscmd/bc'
Makefile:52: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/sparky4/p/elks/elkscmd'
Make.defs:192: recipe for target 'me' failed
make: *** [me] Error 2
Build script has terminated with error 7

flex..

**Comment by sparky4** [comment]
*
* Building image: root
*
umount -d /home/sparky4/p/elks/elkscmd/root >/dev/null 2>&1 || true
dd if=/dev/zero of=/home/sparky4/p/elks/elkscmd/root bs=1024 count=360 2>/dev/null
/sbin/mkfs.minix -n14 -1 -i360 /home/sparky4/p/elks/elkscmd/root >/dev/null
mkdir -p /mnt/elks
mount -o loop /home/sparky4/p/elks/elkscmd/root /mnt/elks
(cd /home/sparky4/p/elks/elkscmd/rootfs_template; \
tar cf - --exclude CVS --exclude .keep *) | \
(cd /mnt/elks; tar xpf -)
for i in sys_utils misc_utils disk_utils file_utils levee minix1 minix2 minix3 ash bc mtools sash sh_utils inet ktcp prems test/eth test/socket/echo test/pty bootblocks; do make -C $i min_rfs || exit 1; done >/dev/null
make[2]: *** No rule to make target 'min_rfs'.  Stop.
Makefile:119: recipe for target '_populate_target' failed
make[1]: *** [_populate_target] Error 1
make[1]: Leaving directory '/home/sparky4/p/elks/elkscmd'
Makefile:209: recipe for target 'root' failed
make: *** [root] Error 2
Build script has terminated with error 8

min_rfs? sigh...

**Comment by mfld-fr** [comment]
Also reproduced that failure with the latest master version. It is coming from the import of the /dev86 `bootblocks` in commit 0deea11. Missing rules for disk image in `bootblocks/Makefile`. Let me fix that Makefile...

**Comment by mfld-fr** [comment]
@sparky4 : please update your local clone and test again.

**Comment by mfld-fr** [comment]
@jbruchon : thanks for the quick pull (as usual). I think you could also close this issue.
