### ISSUE TITLE
Can not boot no HD image with supplied qemu.sh script

### ISSUE THREAD

**Issue by rafael2k** [ghaerr/elks#1952]
While I can boot floppy disks (with -fda or the long options), with any harddrive image, kernel freezes (for hd64-minix.img) at 
"bioshd: hda BIOS CHS 129,16,63".

Is this issue related to this?
https://github.com/ghaerr/elks/issues/348

**Comment by rafael2k** [comment]
Also this issue is interesting:
https://github.com/ghaerr/elks/issues/199#

Btw, trying the image/hd32mbr-minix.img (with the "-fat" the error is the same) I get stuck at:
bioshd: hda BIOS CHS 62,16,63
(and freezes here)

**Comment by rafael2k** [comment]
![screenshot](https://github.com/user-attachments/assets/965b4e95-2adb-450e-9eea-a1c69a6fff6e)

**Comment by ghaerr** [comment]
Thanks @rafael2k, I've repeated the problem over here but haven't had time to look into it yet - something seems broken indeed. Will advise shortly.

**Comment by rafael2k** [comment]
Thanks @ghaerr!

**Comment by ghaerr** [comment]
Thanks for testing @rafael2k!! 

This was totally broken likely due to some header file changes made previously. All HD boots were affected when CONFIG_IDE_PROBE (default ON) was set, but they're fixed now. The reasons are unrelated to the couple previous issues you mentioned.

**Comment by rafael2k** [comment]
That was fast!
: )
Working now.
