### ISSUE TITLE
Tandy 1000HX Nano-X apps not work

### ISSUE THREAD

**Issue by astrobleem** [ghaerr/elks#1994]
**Description**
- What is expected ? launching any nx* binary to i change graphics mode and display the payload
- What is observed ? 
nothing really happens. it just sits there. I am able to hit control + C and return to shell.

**Configuration**
- Version (commit or release): 0.7.0
- Emulator or HW platform: Using x86box configured as a Tandy 1000HX with NEC V20 CPU. 

**How to reproduce ?**
- Does the problem always happen ? yes, whenever the machine is configured as a Tandy. It works when configured as an XT with EGA. I acknowledge these are two completely different display systems.
- List the steps to reproduce the problem.

**Raw data**
- Screenshot(s):
- 
![image](https://github.com/user-attachments/assets/c594c1e0-e4a9-4f31-9ad2-633dc8b227a7)

- Log file:

**Additional information**
is this Nano-X possible with TGA?

**Comment by toncho11** [comment]
I think not. I think there are VGA, CGA and PC98. For the CGA you need to also recompile the apps with the CGA driver enabled (instead of the default VGA). Your screenshot looks exactly as when VGA is not responding because it writes to the VGA video memory and nothing happens.

**Comment by astrobleem** [comment]
http://ftp.oldskool.org/pub/tvdog/tandy1000/documents/egat1k.txt
http://www.oldskool.org/guides/tvdog/1kfaq.html#IV.D
contains some information which might be useful. 
"The Tandy BIOS fails to set the Video Configuration Code byte at 0040:008A. The default value of this byte is 3Fh. The correct values are: 0Bh, for a single VGA color card; 0Ch, for a dual-monitor system with VGA color and MDA mono; 0Dh, for a single VGA mono board; and 0Eh, for a dual-monitor system with mono VGA and MDA."
![image](https://github.com/user-attachments/assets/92ddee6a-60d3-4c99-8414-d4e5988eb99f)

**Comment by ghaerr** [comment]
> The Tandy BIOS fails to set the Video Configuration Code byte at 0040:008A. 

Neither ELKS nor Nano-X use the BIOS byte you mention, so that is not the issue. I think the problem is that the Tandy 1000HX display hardware is not CGA, EGA or VGA compatible in graphics modes, is that correct? That is, other graphics programs (e.g. DOS games) don't run on the Tandy, or do they? 

> For the CGA you need to also recompile the apps with the CGA driver enabled (instead of the default VGA). 

Nano-X requires a specific graphics display driver to be compiled and linked into its application. We have EGA and CGA compatible drivers only. The EGA driver will also work on VGA but uses only EGA hardware features.

**Comment by ghaerr** [comment]
If it is the case that the Tandy is not EGA compatible, you could write a new driver if you're willing. Or perhaps modify the EGA driver to work. The first step would be to find tech specs and hopefully programming manual on the display hardware.

**Comment by ghaerr** [comment]
Ok, I was just reading about the Tandy 1000HX and their TGA display. Apparently it is CGA compatible. This means that you'll need to recompile the nano-X games you want to run using the CGA driver. 

@tyama501 can give instructions for how that is done, I think it is done by unsetting the CONFIG_HW_VGA in your .config file and recompiling nano-X or the system. He may also have some pre-built binaries that you could test with.

**Comment by toncho11** [comment]
Here is the discussion on the CGA driver: https://github.com/ghaerr/elks/discussions/1939 You need to scroll down.
And in another thread and specifically this reply: https://github.com/ghaerr/elks/discussions/1940#discussioncomment-10255343 is what you need! A CGA compiled nxtetris that will gives us clues on how compatible is Tandy with CGA.

**Comment by tyama501** [comment]
Hi @astrobleem 

Yes, you can try the nxteric that is posted on 
https://github.com/ghaerr/elks/discussions/1940#discussioncomment-10255343
as @toncho11 mentioned.

It uses Int10 BIOS for mode setting so it may not work if that is not supported on the system.

Thank you,
