### ISSUE TITLE
Problem with wiki main page

### ISSUE THREAD

**Issue by toncho11** [ghaerr/elks#2068]
Wiki home page disappeared.
I created a page called "Edit" and later I noticed that the Home page of the wiki is not accessible any more. Not sure it is related.
@ghaerr can you check on your admin side?

**Comment by toncho11** [comment]
You can clone the wiki with: https://github.com/ghaerr/elks.wiki.git

Here is old Home page before it was somehow replaced when I added a new page called "Editor". Sorry about that. 
[elks_home_page.txt](https://github.com/user-attachments/files/17278618/elks_home_page.txt)

I won't try to fix it before we are sure what is happening.
The home page was replaced by me even if they are called differently.

**Comment by ghaerr** [comment]
Ok @toncho11, not sure what happened. I cloned the repo and went back to the first HEAD that had a working Home.md and added that back again... so you might want to check if your last couple changes to Home.md are what you wanted. The edits you made to other pages should still be intact.

Thank you!

**Comment by toncho11** [comment]
Yes. It's OK. Thank you. 
One should never create a wiki page called "Editor" because it overwrites the Home page
