### ISSUE TITLE
Weak implementation of select()

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#208]
Current implementation of `select()` watches the regular wait queues through a special `select_poll` wait queue and a `pollhash` of the watched ones. But the hash is the same for two wait queues in the same address range of 256 bytes (see `select.c` line 57). This is the case for the queues in the NE2K driver. As reported by @Mellvik in #133, effect is to wake up `ktcp` on a write completion while it is waiting for a read completion, and to iterate for nothing on the file descriptors.

**Comment by Mellvik** [comment]
This makes sense, but does it explain why a keypush (probably ntty.c) consistently wakes the Ethernet driver?

**Comment by mfld-fr** [comment]
I don't know for now, as I am investigating and killing the bugs one after one :smile:.

**Comment by mfld-fr** [comment]
To be exact, it is not the key push that wakes up the Ethernet driver. The driver is passive by nature, reacts to NE2K interrupts, and then wakes up the process (here `ktcp`) that was waiting for any incoming data during a blocking `read()` or `select()`.

I am currently testing my fix to this `select()` weakness, and I can see now a correct workflow (no more endless looping) plus an improved performance with ktcp and telnetd, using `busybox telnet 127.0.0.1 2323` on the host and QEMU for ELKS target.

But I can also see the third problem you reported : sometimes part of the output of the remote command is directed to the ELKS console in QEMU, and not to the remote client, even if not logged in ! I am going to open another issue to track that particular problem, because I guess it is not related to the select() implementation.

**Comment by mfld-fr** [comment]
Bad redirection tracked by #211.
