### ISSUE TITLE
Create a new integration branch to host the toolchain migration

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#221]
@jbruchon : as the toolchain migration would make ELKS unstable for quite a long time until we complete and mature the changes, I think it would be safer to branch from master into another one dedicated to that migration.

If you agree, could you then please create that new branch from master, and also set up both as protected in the project configuration ?

**Comment by mfld-fr** [comment]
Hello @jbruchon, I expect you are in a better shape and will be fully back with us soon. Have you recovered enough to process this request ? Looking forward to get your news.

**Comment by mfld-fr** [comment]
Looks like @jbruchon is not available these times. Will stabilize in my own branch before pushing to upstream.

**Comment by jbruchon** [comment]
I'm around, just busy with other things.

**Comment by jbruchon** [comment]
How's this? https://github.com/jbruchon/elks/tree/switch-to-gcc

**Comment by mfld-fr** [comment]
Looks fine, thanks, just missing the protection on both branches.

**Comment by jbruchon** [comment]
What do you mean by "protected?"

**Comment by jbruchon** [comment]
Never mind, I got it.

**Comment by mfld-fr** [comment]
That working branch has been merged to main, could you please delete it now ? Thanks.

**Comment by jbruchon** [comment]
Deleted.
