### ISSUE TITLE
Internet access

### ISSUE THREAD

**Issue by toncho11** [ghaerr/elks#244]
Can I connect it to the Internet with serial null modem or serial to ethernet adapter? There is a TCP/IP stack? But then drivers might be needed or terminal program to dial up? Can I use mutt to check e-mail?

**Comment by mfld-fr** [comment]
Yes, ELKS has a TCP/IP stack, and provides two ways to connect to internet : SLIP (through the serial line) or  Ethernet (through a NE2K compatible ISA board).

Please read the documentation for details: `Documentation/text/networking*`
