### ISSUE TITLE
Compile a program for ELKS

### ISSUE THREAD

**Issue by toncho11** [ghaerr/elks#250]
I have to use the same compiler gcc-ia16 to compile my first C program for ELKS.

Are there any special flags to use to target an Intel 8086 CPU or the fact that it is a 16 bit compiler is enough?

**Comment by mfld-fr** [comment]
Please have a look to `elks/libc/Makefile.inc`. It contains all the flags needed for GCC-IA16. You could also take `elks/elkscmd/sash/Makefile` as an example for your program.
