### ISSUE TITLE
Find cannot get path from environment

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#275]
Find command in ELKS not working as expected. When I do "find ." from ELKS command prompt it says "find: can't get path from environment". But when I do "env" command I see my PATH defined. Also "echo $PATH" returns correct PATH.

Reported by Derek Johansen on the mailing list:
https://www.spinics.net/lists/linux-8086/msg00893.html

**Comment by tkchia** [comment]
Hello @mfld-fr,

I happen to have encountered a bug in `libc/crt0.S` which might be related (see my pull request https://github.com/jbruchon/elks/pull/279).

Thank you!

**Comment by mfld-fr** [comment]
Reproduced on latest master. Going to process @tkchia fix and test again after it.

**Comment by mfld-fr** [comment]
Fixed by 878f6640 and merged in #279.
