### ISSUE TITLE
ELKSEmu clean fails

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#283]
Hello @tkchia,

Some users report on the mailing list that the main `build.sh` fails when doing cleanup from a fresh clone here:
```
clean:
	$(MAKE) -C elksemu clean
```

Could you please have a look ? It looks like related to your "ELKSEmu rescue" recently.

Thanks !

**Comment by tkchia** [comment]
Hello @mfld-fr,

Argh --- my mistake.  I have submitted a pull request which should fix the problem.

Thank you!
