### ISSUE TITLE
Move ELKS ownership to an organization

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#289]
Today I spend much time to rebuild and test ELKS on two main configurations (one for the standard PC and another for my SBC), after processing almost every PR or making some critical changes, and even with that testing discipline, I often miss some regressions.

So I think it is time now to implement a CI to automatically build and perform some sanity checks before the PR, or after any commit, to save our already limited time out of these repetitive tasks (and open a way to setup an automatic deployment of the releases in the form of 'ready-to-use' binary packages for end users, but personally I won't invest time into that direction, as explained in #276).

To begin the CI workflow, one need to be able to change the project settings in GitHub (especially the web hooks / actions / apps to dialog with a CI server). Currently I am only a collaborator in this repository, and have no access to that settings. As far as I know, only the owner of the repository could do that.

I don't want to challenge the current ownership, but need to have such access. One solution is to create an 'ELKS' organization, transfer the ownership of this repository to that organization, and setup permissions in a more fine-grained way.

@jbruchon : if you agree that proposal, could you please create such organization and set me as a member ?

**Comment by jbruchon** [comment]
Done. Have fun.

**Comment by ghaerr** [comment]
(Moved to #290)

**Comment by Mellvik** [comment]
﻿I strongly support this proposal. The recent infusion of energy into the project is inspiring. It is also a good time to reflect on the goals of the project, in order to focus whatever our collective eneriges may accomplish towards something both useful and achievable. 

I may have opinions in that regard, but since my contributions (so far) are testing only, I'll rest my case for now.

Thanks for all the good work. 

Mellvik

**Comment by mfld-fr** [comment]
@Mellvik : Testers are as important as coders, and your testing helped much in tuning the networking, the console and the FAT features. Thanks for your support !

**Comment by mfld-fr** [comment]
@jbruchon : thank you very much for the move and your trust ! Would you have any concern if we short the 'id' of the organization to 'elks' (but keep the full 'name' as it is) ?

Edit: just seen that 'elks' is already taken... 😞 

Edit 2: 'elks-org' ?

**Comment by mfld-fr** [comment]
@ghaerr : moved your proposal to #290 to separate the threads and ease the discussion. This issue addresses only the organization setup.

**Comment by jbruchon** [comment]
@mfld-fr I have not done much of value for ELKS in some time; I'm fine handing ELKS and its future over to you. I don't have time to devote to it for the foreseeable future. You have "owner" status on the organization, so you may push through whatever changes you wish. I'll be shutting off project notifications to myself, though I'll probably leave myself as an "owner" on the new organization in case I change my mind and want to dive back in one day. Good luck and godspeed, friends.

**Comment by mfld-fr** [comment]
@jbruchon : yeah, no value... really nothing... you just rescued the project in its dark times and saved us from the @lkundrak's syndrome 😆 

More seriously, I think that giving ownership to that new organization would save again the project when my turn to switch to other activities will come... that's how the life goes on...

Thank you again for all these years to handle the project, and for your support to enter, understand and contribute to that lovely Linux little brother !

**Comment by jbruchon** [comment]
I'm happy to have done it. It was a miracle that I got my hands on it in the first place, and I feel like cleaning out all the garbage "wishful thinking" config options and writing `build.sh` were the biggest contributions I made to the project outside of simply keeping it from death. Keeping the build process newbie-accessible is top priority. In the new world of relying on a specialized version of GCC, please keep that in mind. Build troubles will be a constant source of pain, so anything you can do to reduce that will pay off ten times what you put into them.

**Comment by Mellvik** [comment]
First of all let me second the kudos to Jody for being the 'rescuer'. Whatever the other contributions are, the rescue itself and the energy delivered was THE life saver for ELKS.

Secondly, and quite possibly repeating myself, the key benefit and potential I see in ELKS is becoming the ultimate tool for 'low resource hardware' - typically vintage PCs and SoCs. Most of us probably have pet projects - systems or hardware we'd like to either bring back to life or make more useful. On many of these systems we can boot some version of MSDOS, maybe even FreeDOS, but getting closer to the hardware, which ELKS makes possible, is the ultimate debugging tool. 

I'm rambling. What I'm really saying is I'm happy ELKS is here, and I look forward to follow the project from the sideline, testing on real hardware whenever I have time and/or someone asks. I have a stack of Compaq portables (III/286, 386, and the like, serial (ISA) cards, Ethernet cards etc.). Odd as they are, they present some peculiar challenges @ the BIOS level. 

I also have a (formerly mentioned) ambition to get ELKS running on the Lantronix Xport, now quite old, but a fun size factor containing a 80186 core and some other (meager) resources. Look it up - this is an ethernet connector that happens to have an SoC inside. Running ELKS - eventually.

Helge (aka Mellvik)
