### ISSUE TITLE
Reading from /dev/fd1 yields contents of /dev/fd0 ?

### ISSUE THREAD

**Issue by tkchia** [ghaerr/elks#313]
I ran ELKS under QEMU, with a 1.44 MiB disk image for ELKS in drive A:, and a 720 KiB FAT12 disk image in drive B:.

Dumping the contents of `/dev/fd0` and `/dev/fd1` in ELKS yields identical results for some reason, even though ELKS correctly figures out that their drive geometries and filesystems are different:

![20200208-1](https://user-images.githubusercontent.com/5507843/74083194-225b8c00-4a9c-11ea-954a-d0d94245a0f6.png)

Thank you!

**Comment by tkchia** [comment]
This bug seems to only affect attempts to read directly from the `/dev/fd1` block device file.  Mounting `/dev/fd1` at a mount point and reading files from the mounted volume seem to work normally.

The bug also seems to also crop up when I run `head -1 /dev/bda`.

Thank you!

**Comment by mfld-fr** [comment]
Mmm... looks like a bug around the CONFIG_BLK_DEV_CHAR option and the code to present a block device as a flat file...

**Comment by tkchia** [comment]
I found the bug (`inode->i_dev` was used instead of `inode->i_rdev`), and `head -1 /dev/fd1` works correctly now:

![20200210-1](https://user-images.githubusercontent.com/5507843/74153199-0ba76780-4c4b-11ea-8105-acd346ac7928.png)

Thank you!

**Comment by mfld-fr** [comment]
Thank you @tkchia for the fix !
