### ISSUE TITLE
Disk images missing in releases

### ISSUE THREAD

**Issue by georgp24** [ghaerr/elks#317]
The page https://github.com/elks-org/elks/releases offers ELKS releases for download. The 0.2.0 release contained ready-to-run disk images. 
Could disk images be added for the 0.3.0 release as well?

**Comment by mfld-fr** [comment]
No disk images will be added to a past release.

The new CI automatically generates the default image `fd1440.bin` for you in the `main` workflow : https://github.com/elks-org/elks/actions?query=workflow%3Amain

Go to the latest successful run, and pickup the artifact.

In the next release, more images will be automatically posted, thanks to the 'package manager' from @ghaerr.

**Comment by mfld-fr** [comment]
See also #290
