### ISSUE TITLE
Revert disputed commits to allow getting back to work

### ISSUE THREAD

**Issue by ghaerr** [ghaerr/elks#354]
I don't now how to open a PR to revert a commit, so I am opening a this issue.

The three commits listed below are what caused the decision of myself (@ghaerr) and @tkchia to stop continued contributions to this repository, especially since they were not committed through the normal pull release discussion process. As such, they should be reverted, after which @mfld-fr can open a PR and go through the standard process if desired.

<img width="1321" alt="ELKS commits" src="https://user-images.githubusercontent.com/11985637/74996845-ee745500-5411-11ea-89c7-00f1f529715c.png">

**Comment by jbruchon** [comment]
In your fork, you `git branch newbranchname`, then `git checkout newbranchname`, then `git revert commit1 commit2 ...` with each commit listed to be reverted, which will produce a new commit that reverts them. Then you'd issue a PR for that branch. After the PR is merged into master, you can delete the branch from your local repo.

**Comment by ghaerr** [comment]
Thank you. I'll wait and make sure @tkchia supports this approach and then submit a PR.

**Comment by jbruchon** [comment]
While you and @tkchia are looking at this, I'd also like the 2 outstanding pull requests reviewed. There are a lot of patches underneath those requests and they should be discussed and potentially merged as soon as possible.

**Comment by ghaerr** [comment]
#332 is definitely on hold until after this release, considered too untested to add at this point.

#350 appears quite messed up: it contains lots of other commits, when it's only supposed to contain the 3rd set of additions for BusyELKS from Marcin. Notice that it also pulled over the big disputed conversation from one of the 3 disputed commits - that is definitely not supposed to be part of the commit. I am only guessing that perhaps it got messed up with the recent HEAD readjustments. The 3rd set of additions for BusyELKS would be nice to add, but we need to find a clean copy first.

**Comment by ghaerr** [comment]
I now see the problem with #350 is that it's a PR from @mfld-fr 's marcin branch, which he's apparently also using to rebuild his fork when the HEAD changed, so it now includes other stuff as well.

**Comment by mfld-fr** [comment]
You can delete the 'marcin' branch, I am waiting first for the situation to stabilize, then I will repush Marcin's patches.

**Comment by tkchia** [comment]
Hello @ghaerr,

> I'll wait and make sure @tkchia supports this approach and then submit a PR.

Yes, I am fine with this.

I will also try to jot down my observations on the `ino_t` problem soon (it is a _little_ bit more complicated than I initially thought).

Thank you!

**Comment by ghaerr** [comment]
> > I'll wait and make sure @tkchia supports this approach and then submit a PR.
> 
> Yes, I am fine with this.

Great, I'll get a PR ready. I'm a little tight on time this weekend, but will get to it least by Monday.
