### ISSUE TITLE
ELKS now hangs at startup?  "Running /etc/rc.d/rc.sys script"

### ISSUE THREAD

**Issue by tkchia** [ghaerr/elks#371]
For some reason the merge commit c1cddd353ea52ac6e0add0088fb2bbb36fd5b9ac (or thereabouts) is causing ELKS to hang under QEMU:

![20200223](https://user-images.githubusercontent.com/5507843/75110587-d0edf800-566a-11ea-8eb0-e60b73d2615f.png)

This is, of course, making it a bit difficult for me to do further work on ELKS.

Any ideas what might be causing this?  Thank you!

**Comment by tkchia** [comment]
Hello all,

It seems the `clock -s` command in `/etc/rc.d/rc.sys` was acting up.  I hope to figure out what exactly went wrong (help will be welcome).  Thank you!

**Comment by mfld-fr** [comment]
Wrong design. HW specific code to be in the kernel. Not in user application.

**Comment by tkchia** [comment]
It seems that I accidentally linked `clock.c` with an old broken version of `getopt` which caused `clock -s` to go into an infinite loop.  Once I rebuild everything and confirm this, I will close this issue.

Thank you!

**Comment by tkchia** [comment]
Yes, it turns out that the broken `getopt` was indeed the issue.

(@mfld-fr: you do have a point --- it might be good for the kernel to support an additional device file like `/dev/rtc0` for operations on the real-time clock.  But it is probably not a critical flaw to allow applications to access hardware directly.  Linux itself does have `iopl` and `ioperm` syscalls to allow just that, after all.)

Thank you!

**Comment by jbruchon** [comment]
In real mode, you can't really stop applications from doing anything they want to do. That being said, an RTC device would make common clock code accessible to more than one program without having to include that code.

**Comment by ghaerr** [comment]
> Wrong design. HW specific code to be in the kernel. Not in user application.

Agreed. Although that wasn't actually the problem here. It seems that changing the getopt.c file didn't cause clock to be rebuilt... so a Makefile problem as well.

> Yes, it turns out that the broken `getopt` was indeed the issue.

Strange how the replaced `getopt` didn't force a remake.


>  But it is probably not a critical flaw to allow applications to access hardware directly. Linux itself does have `iopl` and `ioperm` syscalls to allow just that, after all.)

In any case, the idea that user programs should have non-portable `asm` calls embedded in C code and not use at least a library call for interrupts on/off or a kernel call as @mfld-fr suggested will just lead to more trouble. If we're going to be strict on maintaining ABIs elsewhere all hardware ifdefs around `asm` calls should be eliminated. This isn't necessarily about where the function lives (libc or kernel) but instead keeping user land C files using some provided ABI and no ifdefs.

**Comment by tkchia** [comment]
Hello @ghaerr,

> If we're going to be strict on maintaining ABIs elsewhere all hardware ifdefs around `asm` calls should be eliminated.

Agreed.  Thank you!

**Comment by tkchia** [comment]
Hello @ghaerr,

> It seems that changing the getopt.c file didn't cause clock to be rebuilt... so a Makefile problem as well.

It turns out that I was linking against an `elks-libc` from a different toolchain installation (i.e. not under `elks/cross/`), which caused the problem.

Thank you!

**Comment by Mellvik** [comment]
@tkchia,
I still think the issue needs investigation. I had the same problem when debugging, and only one toolchain installation. It was my impression that the problem was libc not being rebuilt automatically when getopt.c changed.

--Mellvik

**Comment by tkchia** [comment]
Hello @Mellvik,

Argh!  It seems you are right --- the dependency checking which I wrote for the `libc` makefile is apparently not as strong as it should be.  I am submitting a patch (https://github.com/jbruchon/elks/pull/381) to fix this.

Thank you!
