### ISSUE TITLE
XT IDE hdd detection results in system crash

### ISSUE THREAD

**Issue by sparky4** [ghaerr/elks#39]
My XT has an XTIDE card in it and when elks trys to look for a HDD, it crashes.... ><
I am reporting this issue and i can also provide screen photos of the crash. ^^;

http://4ch.mooo.com/4/xtssd/ the card i have is this

**Comment by mfld-fr** [comment]
Hello, thanks for the report, yes your screenshots would be appreciated to help.

**Comment by jbruchon** [comment]
I'd also like to see some screenshots of this crash.

**Comment by sparky4** [comment]
oh my i apologize for long response! ok i will photo take with latest version. damn it school!

**Comment by sparky4** [comment]
ok photos soon going to compile and make xt boot
![img_20161007_150615471](https://cloud.githubusercontent.com/assets/8118902/19203998/0a8adada-8ca0-11e6-9ae8-0d79b038fbb8.jpg)
![img_20161007_150616747](https://cloud.githubusercontent.com/assets/8118902/19204001/0a8ce4ce-8ca0-11e6-936b-62c802dcc2d1.jpg)
![img_20161007_150616929](https://cloud.githubusercontent.com/assets/8118902/19204002/0a8f1992-8ca0-11e6-8275-b3c4f9fcd23b.jpg)
![img_20161007_150617111](https://cloud.githubusercontent.com/assets/8118902/19203999/0a8b9916-8ca0-11e6-9122-d7a4bf4db179.jpg)
![img_20161007_150617292](https://cloud.githubusercontent.com/assets/8118902/19204000/0a8c2944-8ca0-11e6-8643-584c9dd3f091.jpg)
![img_20161007_150645090](https://cloud.githubusercontent.com/assets/8118902/19203997/0a8a5ec0-8ca0-11e6-9c97-f64700683097.jpg)
![img_20161007_150647158](https://cloud.githubusercontent.com/assets/8118902/19204003/0aa0dc22-8ca0-11e6-880c-12b0547e6b5c.jpg)
![img_20161007_150648504](https://cloud.githubusercontent.com/assets/8118902/19204005/0aa3fd80-8ca0-11e6-9a91-abf2bd7a2fde.jpg)
![img_20161007_150654050](https://cloud.githubusercontent.com/assets/8118902/19204004/0aa2d676-8ca0-11e6-8fa4-4a8fce934253.jpg)
![img_20161007_150655936](https://cloud.githubusercontent.com/assets/8118902/19204006/0aa6eb80-8ca0-11e6-9bac-defe061dc486.jpg)
![img_20161007_150658755](https://cloud.githubusercontent.com/assets/8118902/19204007/0aa7f1ec-8ca0-11e6-82a4-bf28888d1363.jpg)
![img_20161007_150702664](https://cloud.githubusercontent.com/assets/8118902/19204008/0aaae42e-8ca0-11e6-8fc4-a6f093857648.jpg)
![img_20161007_150704546](https://cloud.githubusercontent.com/assets/8118902/19204009/0ab680ae-8ca0-11e6-9d31-39bd620644bb.jpg)
![img_20161007_150706254](https://cloud.githubusercontent.com/assets/8118902/19204010/0ab92fa2-8ca0-11e6-907e-80493bb048d0.jpg)
![img_20161007_150707486](https://cloud.githubusercontent.com/assets/8118902/19204011/0ab9aed2-8ca0-11e6-8c16-b0ca7fdaf95c.jpg)
![img_20161007_150708907](https://cloud.githubusercontent.com/assets/8118902/19204012/0abc7338-8ca0-11e6-979b-2822dce3af85.jpg)
here it is!

**Comment by hufon** [comment]
I've exactly the same error on my olivetti PC1! which have no hard disk at all... So this is not an hard disk issue.
![img_20161008_141626](https://cloud.githubusercontent.com/assets/1788150/19213075/10672266-8d62-11e6-87ae-acd19c66f60d.jpg)

**Comment by hufon** [comment]
I'm using the comb_net image

**Comment by hufon** [comment]
same problem with comb image...

**Comment by sparky4** [comment]
i amusing comb_net also

**Comment by jbruchon** [comment]
It is a kernel issue so it will affect all disk images.

**Comment by sparky4** [comment]
ah~ ok sorry about my late responce

**Comment by hufon** [comment]
May be you should rename the issue...

**Comment by lithoxs** [comment]
After seeing the screenshots, what happen is:
1. The initialization reaches the point where the whole kernel is set up succesfully, including the floppy and hard disk driver.
2. Succesfully forks the task that mounts the root directory and succesfully mounts the root drive.
3. The above task attempts to exec the "init" task. At this point the said screenshots were taken.
    The exec syscall first tries to find the binary in the disk and this is the point when it fails. In the first
    screenshot, attempts to exec "/bin/init", and the reported error 4 is "Sector not found". Then tries to                                                  exec "/bin/sh" reporting the same error in the same sector, suggesting that it cannot access even the directory.

Now, the disk driver does not touch the hardware, every thing is done through the int 13h bios interrupt. Further, it only uses the CHS addressing, and never LBA addressing.

I understand that your hardware and disk drive bios are not standard. Also, the needs by ELKS correspond to obsolete hardware. So, does your bios implement what ELKS need?. Is it possible to have a look at the source code of your disk bios?.

**Comment by hufon** [comment]
I've no hard disk on my PC1. Only one floppy drive.
It don't works also with 0.2 version.

The drive sounds bad when it fails (like a bad sector on a floppy), but the floppy drive and the floppy disk are both ok

**Comment by hufon** [comment]
It's strange because we use both all different PC model... all PC compatibles (mine is without any addon card, standard 1987 bios)

**Comment by lithoxs** [comment]
The error indication is when attempts to access block device 0x380 both on sparky4 and hufon machines (according to screenshots), and this number corresponds to the first floppy disk. So, that is correct.

The screenshots indicate failure when attempting to read sector 34. This corresponds to a 2.88 Mbyte floppy disk with a geometry of 80 tracks, 36 sectors and 2 heads. If this is not your floppy then the driver is failing to detect the geometry of your floppy disk. Is this your case?

**Comment by hufon** [comment]
I've a dd 720Ko floppy disk 80 track, 9 sector, 2 heads. My Floppy drive is dd only and my floppy controller can only handle dd floppy.
So it seems that the floppy driver fails to detect the geometry of my floppy disk.

**Comment by sparky4** [comment]
any update?

**Comment by jbruchon** [comment]
I just noticed that the "pre-set floppy types" menuconfig option is set up to ignore manual input and assume 2.88M drives. @sparky4 what type of floppy drive do you have? 720K, 1.44M?

**Comment by sparky4** [comment]
!! on my XT i believe it is a 720k one

**Comment by lithoxs** [comment]
Looking for the problem I found another bug in the disk driver. I posted the fix for it. Probably this will not solve this issue. Now I suspect the problem begins when mounting the root filesystem. When mounting root, ELKS will print the following:

fd: probing disc in /dev/fd0
fd: /dev/fd0 probably has 18 sectors and 80 cylinders
.....
VFS: Mounted root (minix filesystem)

The number of sectors and cylinders reported may vary, It also may print an error indication.
What prints in your system?

**Comment by lithoxs** [comment]
I just posted a pull request that might solve this issue. The problem is produced by a weird behavior of the int 13 BIOS with 720K floppies. Please make tests to confirm that the problem is solved.

**Comment by hufon** [comment]
Ok, the problem is solved for me...
Thanks!!!

**Comment by hufon** [comment]
I've another problem (not related) with my CF XTIDE adapter i'll open a new bug

**Comment by sparky4** [comment]
ok i will test soon my AC unit got mold and it is hard to test i will pull latest version and test

**Comment by sparky4** [comment]
it is defiantly fixed ^^ <3

**Comment by mfld-fr** [comment]
Fixed by #44
