### ISSUE TITLE
Make config fails on OSX after busyELKS commit

### ISSUE THREAD

**Issue by ghaerr** [ghaerr/elks#395]
It appears that `make config` doesn't handle the new `busyelks` command that is in `elkscmd/config.in` and `config/Menuconfig`, so it is failing with the following error:

```
 * Other commands
 *
bc (CONFIG_APP_BC) [Y/n/?] 
busyelks (CONFIG_APP_BUSYELKS) [Y/n/?] 
dbgutils (CONFIG_APP_DBG_UTILS) [Y/n/?] 
elkscmd/config.in: line 25: busyelks: command not found
elvis (CONFIG_APP_ELVIS) [Y/n/?] 
elkscmd/config.in: line 27: busyelks: command not found
levee (CONFIG_APP_LEVEE) [Y/n/?] 
m4 (CONFIG_APP_M4) [Y/n/?] 
elkscmd/config.in: line 30: busyelks: command not found
minix2 (CONFIG_APP_MINIX2) [Y/n/?] 
elkscmd/config.in: line 32: busyelks: command not found
elkscmd/config.in: line 33: busyelks: command not found
mtools (CONFIG_APP_MTOOLS) [Y/n/?] 
```

`make config` runs with errors but `make menuconfig` hasn't ever worked on OSX, so now I'm unable to produce a working .config file and build ELKS.

@marcin-laszewski: Do you have any thoughts about how to get this to work, other than reverting back to replacing `busyelks` with `bool` in `elkscmd/config.in`? It appears that perhaps `config/Configure` also needs the `busyelks` function(s) that were added to `config/Menuconfig`?

**Comment by marcin-laszewski** [comment]
Fixed: #397 (I hope).
