### ISSUE TITLE
Build-time regression: error: unrecognized command line option '-maout-chmem=0xc000'

### ISSUE THREAD

**Issue by pawosm-arm** [ghaerr/elks#399]
This commit: 3f1187c92432cf7633aa9b425e6c6d8abb5c0c03 causes following link-time error:
```
ia16-elf-gcc -o fbc -fno-inline -melks-libc -mcmodel=small -mno-segment-relocation-stuff -mtune=i8086 -Wall -Os -maout-chmem=0xc000 bc.o scan.o util.o main.o number.o storage.o load.o execute.o  global.o 
ia16-elf-gcc: error: unrecognized command line option '-maout-chmem=0xc000'
make[2]: *** [Makefile:57: fbc] Error 1
```

**Comment by jbruchon** [comment]
You need to build the latest ia16-gcc.

**Comment by tkchia** [comment]
Hello @pawosm-arm,

Most probably you had previously installed a slightly older version of the toolchain,  You need to download and build a newer version of the `gcc-ia16` development toolchain, which should support the `-maout-chmem=` option.  You can do that by running `tools/build.sh`.

Thank you!

**Comment by pawosm-arm** [comment]
All it needs is to delete the `cross` directory. Doing it now, it will take some time to build.

**Comment by pawosm-arm** [comment]
Indeed, it builds now. Closing it.
