### ISSUE TITLE
Delay loop calibration fails

### ISSUE THREAD

**Issue by pawosm-arm** [ghaerr/elks#427]
With `CONFIG_BOGOMIPS=0` set in `.config` I'm observing following message at boot time:
```
Calibrating delay loop... failed
```

**Comment by ghaerr** [comment]
From what I can see, it is only used to set a value for `loops_per_sec`, which then isn't even used anywhere. If that's the case, the whole thing should be deleted.

@mfld-fr, are you aware of whether is used anywhere?

**Comment by mfld-fr** [comment]
Yeah, useless.
