### ISSUE TITLE
Regression: bootloader dots printed with rubbish instead of sending cursor to a new line

### ISSUE THREAD

**Issue by pawosm-arm** [ghaerr/elks#462]
I had pulled in the current master this morning, and I booted what I've built from that.
One visible change is that after bootloader prints a line of dots, the cursor does not go to the newline, it prints couple characters of rubbish and the next boot message is going directly after them (while it should appear in a new line).

I'm booting MINIX HD all-disk image.

Occurs on every reboot.

**Comment by tkchia** [comment]
Hello @pawosm-arm,

Argh!  Sorry for the mistake.  Thankfully, that was just a minor cosmetic bug, and it has been fixed now.

Thank you!

**Comment by pawosm-arm** [comment]
It's ok now, thanks!
