### ISSUE TITLE
sys calls needed for tar()

### ISSUE THREAD

**Issue by Mellvik** [ghaerr/elks#486]
While working on a new tar() for elks, I'm running across some missing syscalls.
One of them is **utimes**, which exists in the source but is commented out (open.c). Further, sys_utimes uses notify_change, which is also commented out (inode.c). I need a recommendation as to how to proceed with this.
Also missing are telldir() and getwd() - again, hints solicited.

--Mellvik

**Comment by ghaerr** [comment]
Its a bit complicated, based on whether you're writing new code within an app, or porting an already-known-working application over. With new code, there's more flexibility is which routines are called and which alternatives might already be implemented.

For wholesale porting, I suggest stubbing out missing routines and placing them at the top of the application source file. Then, the problem can be divided into libc versus kernel issues. For instance, `getwd` should be changed to `getcwd`, as it's safer. `telldir` is best implemented as an add-on in the existing libc `opendir` / `readdir` code as a new function, but might be able to be kept in your application while porting it, then moved to libc.

For `utimes` and other functions, a judgement has to be made as to whether the limited code space kernel expansion is worth it, given its utility for just one command. Initially, this function could be 'faked' within the application and the result would just be that the extracted files don't have the specified timestamp. After the application is working well, discussion can be made regarding kernel add-on.

For things like notify_change, IMO it would be best left out.

Summary - get the application running first, if possible. Update libc if needed. Kernel mods come last.
