### ISSUE TITLE
ttyname() does not return information

### ISSUE THREAD

**Issue by georgp24** [ghaerr/elks#543]
I would like to use the ttyname() function. This program:
```
#include <stdio.h>
#include <unistd.h>

int main() {
    char *tty_name = ttyname(STDIN_FILENO);
    printf("TTY-Name:%s\n",tty_name);
    return 0;
}
```
returns on my Linux system: `TTY-Name:/dev/pts/0`

However, it does not return anything on ELKS. However, there seems to be code for this function here: `elks/libc/termios/ttyname.c`

**Comment by ghaerr** [comment]
Hi @georgp24,

I have debugged this and found that, the kernel `fstat` function call is buggy!! Amazing.

A PR will be forthcoming, thanks.
