### ISSUE TITLE
PCem emulator testing

### ISSUE THREAD

**Issue by ghaerr** [ghaerr/elks#566]
So I just gave a try to fd360-minix.bin in PCem with my 1512 profile and it works great. The only thing you need to do to use these images with PCem is change the file extension to 'img' to load them in. Everything in PCem can be set up from the GUI like VirtualBox so there's not really a big need for a config file. But there is one for each virtual PC config one might brew anyway.

![Screenshot_2020-04-18_14-46-02](https://user-images.githubusercontent.com/359383/79638844-0a814200-8188-11ea-9c61-21266574daa0.png)

![Screenshot_2020-04-18_14-46-15](https://user-images.githubusercontent.com/359383/79638851-140aaa00-8188-11ea-8bb3-8787b9470191.png)

![Screenshot_2020-04-18_14-47-01](https://user-images.githubusercontent.com/359383/79638858-1e2ca880-8188-11ea-9c3d-c9d6791c3a31.png)

I went and ls'ed and cat'ed around the file system and everything works great so far. 'reboot' works too. The system seems to run as fast as I remember MSDOS to run on a real 1512. I could be wrong but the 1512 doesn't have NEC V30 CPU, but an AMD 8086. Maybe PCem got it wrong. The serial ports are indeed two 16550A on the 1512.

Building binutils/gcc with build.sh works great as well. I was able to build a custom 32mb hd image of ELKS after fiddling a bit in menuconfig. However the geometry automatically detected by PCem for the ELKS hd image isn't supported by the MFM controller emulated by PCem that I chose. Going to try out other controllers. This is what I get so far with the hd image in PCem:

![Screenshot_2020-04-18_14-55-22](https://user-images.githubusercontent.com/359383/79638920-96936980-8188-11ea-8e02-016fd1fdd475.png)

_Originally posted by @cjsthompson in https://github.com/jbruchon/elks/issues/372#issuecomment-615870788_

**Comment by ghaerr** [comment]
Hi @cjsthompson, I moved your issue over here to keep it separate from the IRQ discussions.
Thanks for your testing!!

It's interesting looking at a different emulator boot ELKS. I notice that it's found two LPT ports at the same locations as the serial ports. Also, the system seems to think there's one hard drive and 0 floppy drives when booting from floppy, but works anyways.

The reported CHS of 305,8,17 can't always be trusted. some emulator BIOS's calculate that from the real CHS. What settings did you use in `menuconfig`?

Have you tried running "cd images; make images" to make the extra images and booting the standard HD image 'hd32-minix.bin'?

**Comment by cjsthompson** [comment]
I left everything to defaults as far as the HD image settings when I built it. It seems 32mb isn't a standard size for MFM drives. It was 10,20,30,40 mbs. My 1512 has a 40mb MFM Seagate in it.

I am as we speak running menuconfig again to alter the geometry with one I know works with the Xebec MFM controller emulated by PCem. I just need to figure out how to calculate the disk size in 1k blocks for the geometry I put in (17 sectors, 8 heads, 306 cylinders).

Also the 1512 has only one parallel port.

**Comment by ghaerr** [comment]
> It seems 32mb isn't a standard size for MFM drives. 

Definitely not, the 32MB was built to test a large (for ELKS anyways) hard drive and force FAT32 for testing.

> I just need to figure out how to calculate the disk size in 1k blocks for the geometry I put in

[EDIT:] Size in 1k blocks = (C x H x S) * 512 / 1024.

**Comment by cjsthompson** [comment]
With this setup, now I can boot the ELKS hd image in PCem with no problem. 

![Screenshot_2020-04-18_16-42-34](https://user-images.githubusercontent.com/359383/79640888-86818700-8194-11ea-83ca-88e66b33d855.png)

There are interrupt problems however. But I get to the login prompt, can log in, and use commands.

![Screenshot_2020-04-18_16-40-49](https://user-images.githubusercontent.com/359383/79640982-19babc80-8195-11ea-83f2-35e672089ea3.png)

**Comment by ghaerr** [comment]
There was a recent change to enable COM3 and its associated IRQ 5 by default. This IRQ is used by other devices, so it looks like this should be turned off by default.

Modify 'elks/include/arch/ports.h', and comment out the \#define CONFIG_NEED_IRQ5 on line 44, that will fix it.

**Comment by cjsthompson** [comment]
Now everything is working as it should.

[ELKS 0.3.1pre running on PCem v15](https://www.youtube.com/watch?v=MlcYiYBTEHY)
