### ISSUE TITLE
Links not working on ELKS FAQ web pages

### ISSUE THREAD

**Issue by georgp24** [ghaerr/elks#65]
When I load the [http://elks.sourceforge.net/FAQ-English.html](url) web page, I get the following error message when I click on any of the links provided. The same is the case with the web pages in other languages:

-------------------------------------------------------------------------------------------------------------------------

`An error has been encountered in accessing this page.

1. Server: elks.sourceforge.net
2. URL path: /faq/FAQ-English.html
3. Error notes: NONE
4. Error type: 404
5. Request method: GET
6. Request query string: NONE
7. Time: 2017-02-26 11:36:49 UTC (1488109009)

Reporting this problem: The problem you have encountered is with a project web site hosted by SourceForge.net. This issue should be reported to the SourceForge.net-hosted project (not to SourceForge.net).

If this is a severe or recurring/persistent problem, please do one of the following, and provide the error text (numbered 1 through 7, above):

Contact the project via their designated support resources.
Contact the project administrators of this project via email (see the upper right-hand corner of the Project Summary page for their usernames) at user-name@users.sourceforge.net

If you are a maintainer of this web content, please refer to the Site Documentation regarding web services for further assistance.

NOTE: As of 2008-10-23 directory index display has been disabled by default. This option may be re-enabled by the project by placing a file with the name ".htaccess" with this line:

Options +Indexes
`

**Comment by jbruchon** [comment]
I should probably shut that entire domain down and register one for a proper ELKS website. The FAQs are available in the source, I think.

Problems with the website should be sent to the mailing list, not as an issue with the code on Github.
