### ISSUE TITLE
[ktcp] ARP sequencing error

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#67]
The current implementation of the ARP module makes the assumption that the next incoming packet after sending an ARP request will be the expected ARP reply. It works in QEMU, but in a real & more loaded network, some other packets might come between the request and the reply. Therefore the implementation of ARP should be kept asynchronous as the IP module.

**Comment by georgp24** [comment]
At the moment I do not expect a loaded network on ELKS. But I do not object to modify this.

**Comment by mfld-fr** [comment]
In my own roadmap, networking in QEMU is nice but a preliminary step before networking on my real SBC, that is connected to my internet box, and thus "bombed" at a high rate with many packets that come at any time. So this improvement is a must have.

**Comment by georgp24** [comment]
Rereading my post I agree that it indicates that I volunteered to do that. But if you need that I would prefer if you have a go at it.

The ARP request is not triggered by the socket interface but from ip.c resulting from a send packet by an application which is currently in progress. So making this asynchronous is not straightforward.

**Comment by mfld-fr** [comment]
Hello Georg, no problem, I started working on it.

**Comment by jbruchon** [comment]
Is this bug still present?

**Comment by georgp24** [comment]
I cannot test it on real hardware and I expected Marc to fix this.

**Comment by mfld-fr** [comment]
Yes, still present.

**Comment by Mellvik** [comment]
I can't help fix this, but I can do the physical hardware testing. Let me know.

—Mellvik

**Comment by ghaerr** [comment]
This three-year-old issue finally fixed and tested with PR #667. Closing issue.

**Comment by mfld-fr** [comment]
Nice, thank you !
