### ISSUE TITLE
[INFORMATION] How to transfer files to/from elks

### ISSUE THREAD

**Issue by Mellvik** [ghaerr/elks#697]
### Intro
This is an informational post, not a bug report. 

ELKS is rapidly getting closer to being self-sufficient. Being able to transfer files into and out of the system is an important milestone towards that goal. Recent improvements in networking support and serial port reliability & speed have made that possible.

**Serial**
Transferring limited size ascii files can be done with reasonable reliability via serial lines and terminal emulation. `cat > filename`and then paste text into the terminal is reasonably efficient. If this fails marginally, turn off echo in order to reduce the interrupt load on the system:
```
stty raw; cat > filename; stty -raw
```
or use the `sercat` command:
```
sercat > filename
```
Terminate such transfers with ^D (EOF).

To check whether the transfer was error free, use the `sum` command at both ends, after ensuring that the byte count is exactly the same (`ls -l`). Note that it takes only an extra newline or CR at the end of the file to make the `sum` command useless.

Even binary files may be transferred this way by first converting them to ascii. Use the `hexdump` command on Linux:
```
hexdump -e '"%06.6_ax:" 8/1 " %02x" " " 8/1 " %02x" "  " ' -e '16/1 "%_p" "\n"' "$@"
```
to create the ascii file, then `hd -r` on ELKS to convert it back.
A far more efficient (and traditional!) way is using `uuencode` and `uudecode`. Instead of turning 16 bytes into 69 which `hd`does, `uuencode`converts 2 bytes into 3 ascii characters. The commands are part of the uucp package. The (simplified) syntax is
```
uuencode newname < inputfile > outputfile
```
where `newname` is the filename to be used when the file is decoded and recreated. Even the mode (protection codes) of the file is stored in the encoded file and will be recreated during decoding if possible. To decode, simply give the command
```
uudecode < inputfile
```
and the old file (and filename + modes) will be recreated. There are many options to override the defaults, check the man-pages for details.

Taking ascii files from ELKS via serial is usually easy (and fully reliable) since most systems will have no problems keeping up with the speed of the ELKS system.

Mechanisms to make serial transfers binary and fully reliable - Kermit, X/Y/Z-modem etc. - are forthcoming. 

### ELKS networking
ELKS has 'reasonably stable' TCP/IP and Ethernet (ne2k interface), and reliable (albeit slow) file transfer is available both ways. The quality and diversity of this support is changing constantly. Currently, the `urlget` program is the key to move files into ELKS. For outgoing files, the `httpd` server does the job - for now. 
Check that the ethernet interface gets configured correctly during boot:
```
eth: NE2K at 0x300, irq 12, MAC 00:40:C7:21:D7:9F
```
... and use the `ps` command to check that the network is up and running (look for the `ktcp`-process):
```
# ps
  PID   GRP  TTY USER STAT CSEG DSEG  HEAP   FREE   SIZE COMMAND
    1     0      root    S 2f03 30b2  3072   2004  15696 /bin/init 6 
   20    20    1 root    S 5d30 4c04     0   1972  13072 /bin/getty /dev/tty1 
   21    21    2 root    S 5d30 5498     0   1972  13072 /bin/getty /dev/tty2 
   22    22   S0 root    S 3769 42b4  1340   6644  64928 -/bin/sh 
   10    10      root    S 4df6 5edb 13552  22218  69200 ktcp -b 10.0.2.15 10.0.2.2 255.255.255.0 
   13    13      root    S 32d8 4967     0   2012  12320 telnetd 
   16    16      root    S 4ae7 5295     0   2018  12800 httpd 
   23    23   S1 root    S 5d30 57c1     0   1980  13088 /bin/getty /dev/ttyS1 9600 
   24    24   S2 root    S 5d30 5956     0   1980  13088 /bin/getty /dev/ttyS2 9600 
   41    22   S0 root    R 562c 345a  1024   6428  18640 ps 
# 
```
If it's not, run the `net start eth`command, and check that the messages don't indicate an error:
```
# net start eth
Starting networking on eth
ktcp -b 10.0.2.15 10.0.2.2 255.255.255.0
ktcp: ip 10.0.2.15, gateway 10.0.2.2, netmask 255.255.255.0
ktcp: ethernet 00.40.c7.21.d7.9f mtu 1024
Starting daemons telnetd httpd
#
```

**urlget**
`urlget` is a very flexible tool for transferring files into the ELKS system. Three programs in one – `urlget`, `httpget` and `ftpget`, supporting 3 different URLs and 3 protocols: HTTP, FTP and pure TCP (useful with `netcat`) - all requiring a server to talk to at the other end. Not a problem - if such a server is not already running, a python one-liner is normally all it takes to start your own. Which turns out to be preferable even such server is already running. More about that below.

A summary of the command syntax:
```
urlget http://host:port/filepath
urlget http://username:passwd@host:port/filepath
urlget ftp://host/filepath
urlget ftp://username:passwd@host:port/filepath
urlget tcp://host:port/filepath

httpget [-h] [-d] [-p] host filepath
ftpget [-v] host[:port] filepath [username [passwd]]
```
In all variants, the authentication can be omitted if acceptable to the server. If included, the username and passord are sent in plaintext over the network. Also, `port` may be omitted in most cases, which means use the default port - 80 for http, 21 for ftp. Fot `tcp`, the port must be included as there is no standard.
For `ftp`, if the filepath ends with a slash, a directory listing is delivered. The `-v` option to `ftp` enables long (`ls -l`) directory listings. Fot `http`, the `-h` option will include HTTP-headers in the output, `-d` will discard the contents, which is meaningful only with the `-h` option (display headers only), and the `-p` option will `post` data instead of fetching it. The data in this case is whatever follows a '?' in the filepath. This option is currently not very meaningful.

The tcp-url sends the file name, but there is not standard way of handling such request at the other end, see below for a suggestion on how to use this variant.

### INBOUND HOWTO 
Make sure the network is up and running on ELKS: Run `ps` - if `ktcp` is listed, you're ok, of not, run `net start eth`.

If running QEMU, use the default qemu.sh script and make sure this line is 'uncommented': `NET="-netdev user,id=mynet,$FWD -device ne2k_isa,irq=12,netdev=mynet"`

**urlget with http, httpget**
- Start a web server on the host, like a simple python http-server:
  - If you have python V3, run `python3 -m http.server 8000 --bind 127.0.0.1`. If your version is 2 (check by running `python -V` or resort to v3 explicitly if it exists, like `python3`): `python -m SimpleHTTPServer`. If running Windows, the commands may be a little different, Google it to find out.
  - This will make the current directory available for file transfers. 

I you want something more stable, install and run `lighttpd` (see below). If using the default install- and config-files, the files to transfer would be places in a subdirectory of `/var/www/html`. Such as `/var/www/html/elks`. In this case you don't need to specify the port number (8000 above), or just add '80' for the record. Make sure to create the subdirectory and set the access bits. This installation requires root access.
- Put the file(s) you need to transfer into that directory (or a subdirectory).
- Run 
  - [python3/python] `urlget http://10.0.2.2:8000/filename > local_filename` or `urlget http://10.0.2.2:8000/dir1/dir2/filename > local_filename`
  - [lighttpd, other servers] `urlget http://10.0.2.2/elks/filename > local_filename`

**urlget with ftp, ftpget**
If an `ftp` server is already running, you're OK. Check the server config-files to determine if anonymous access is available, and what directory such access is limited to. If you will be using authentication (username and password), ensure your user is allowed incoming ftp access.

FTP:
If no `ftp`-server is running, a`python`-based server is the easy way out, just like the http-example above. `pyftpdlib` must be installed, google it if directions are needed. Run `python3 -m pyftpdlib -p port -u someusername -P somepasswd`. Any name and password will do, not limited to your local username/passwd, but they must match when making a connection. Anonymous authentication is supposed to work, but does not. The default port number is 2121.

Assuming an FTP server running and your user is an allowed ftp-user, you can ftp files into ELKS like this:
```
urlget ftp://user:passwd@host:port/filename > localfile
```
for example
```
urlget ftp://testuser:passwd@10.0.2.2:21/testfile > localfile
```
The port number (in this case :21) is optional. 21 is the default and may be omitted. If the ftp server supports (allows) anonymous ftp, the username and password may be omitted. In that case the public (anonymous) ftp directory is where the file (`testfile`) will be looked for. Otherwise, if you provide you username and password (the are being sent over the network in clear text!), your home directory is the root directory for ftp. If `test file`ends with a slash `/`, then test file is assumed to be a directory, and the slash means 'list this directory. Example:
```
urlget ftp://user:pass@10.0.2.2/
```
which will list the users home directory.

Similarly the syntax for `ftpget` is
```
ftpget [-v] host[:port] filepath [user [passwd]] > localfile
```
The -v (verbose) option is meaningful only when listing directories (filepath has a trailing '/').

TCP:
In many ways the simplest of all variants is 'raw tcp': All you need is `netcat` (nc) on the server, which exists on most Unix and Linux systems.
On the host, start `nc` so that it waits for connections and then transfers a file:
`nc -l 2323 < elksout.txt`
2323 is a randomly selected port number (> 1024), which you need when making the connection from elks:
`urlget tcp://host:port > localfile`
The port number is mandatory since there is no default.
`nc` doesn't know when to terminate the connection so you have to abort it with ^c.

**ftpget and httpget**
`urlget`may be linked to different names which will affect its behaviour. If you use `ftpget` it will use the ftp-protocol and the syntax is like this:
```
ftpget host[:port]  filepath [user [passwd]] > localfile
```
for example
```
ftpget 10.0.2.2 filename username userpw > file
```
Like before, username and password may be omitted if anonymous ftp is supported by the server. And again, if the filename ends with a slash, the name is assumed to be a directory and its content will be displayed. If the command line option -v is used, the directory listing is verbose (like ls -l).

`httpget` follows the same rules, with syntax as specified above:
```
httpget [-h] [-d] [-p] host[:port] filepath > localfile
```

### OUTBOUND HOWTO
As mentioned above, files may be transferred out of an ELKS system using the local http-server. As is the case with inbound files, the procedure is untrivial, but not difficult. 
- Place the file/files to transfer in the `/var/www` directory.
- [QEMU]Use curl or wget to fetch the files: [qemu] `curl http://localhost:8080/filename > filename`.
- [Physical machine] `curl http://10.0.2.15/filename > somename`

In order to access files not in the httpd-directory, symbolic links are useful. For example, if you want to transfer the entire hard disk: `cd /var/www; ln -s /dev/bda myfile`, then use curl from the other end to fetch `myfile`. Be warned, this is going to take some time. As of this writing the transfer speed is about 27k bytes per second on a physical system (386).

As of ultimo august 2020 these mechanisms provide dependable file transfer both ways.

**Comment by ghaerr** [comment]
> On a mac, run python3 -m http.server 8000 --bind 127.0.0.1

I tried this on my system, running macOS 10.14.6, and it only has python 2.7.16 installed. I'm afraid to upgrade python since I have other projects dependent on that version of python.

It would be most convenient to transfer files from the current directory, rather than having to copy them to a web server directory, before pulling them from a running ELKS system.

For initiating file transfers from a host to ELKS, I have looked into implementing POST on ELKS httpd. Unfortunately, it seems even the current distribution BusyBox for Linux doesn't implement POST, but uses a CGI-based shell script to make that work. I'm thinking that perhaps HTTP isn't the method that should be used for file transfers, but something more like rcp, which would easily support globbing on the host side for pushing files, with a minimal rlogind on ELKS.

You mentioned that "hd -r" doesn't always work, can you explain in more detail where the bug is?

Thank you!

**Comment by Mellvik** [comment]
> On a mac, run python3 -m http.server 8000 --bind 127.0.0.1
> 
> I tried this on my system, running macOS 10.14.6, and it only has python 2.7.16 installed. I'm afraid to upgrade python since I have other projects dependent on that version of python.
> 
I have the same. That's why I'm using the python3 command. I forget whether it's included or brew-installed...
> It would be most convenient to transfer files from the current directory, rather than having to copy them to a web server directory, before pulling them from a running ELKS system.
> 
Agreed, that's what the python version is doing. That said, this is not about convenience, but about opportunity - right now. This is possible and works, but certainly not convenient.
> For initiating file transfers from a host to ELKS, I have looked into implementing POST on ELKS httpd. Unfortunately, it seems even the current distribution BusyBox for Linux doesn't implement POST, but uses a CGI-based shell script to make that work. I'm thinking that perhaps HTTP isn't the method that should be used for file transfers, but something more like rcp, which would easily support globbing on the host side for pushing files, with a minimal rlogind on ELKS.
> 
Right now we just need something that works. Urlget works inbound, curl/wget outbound seems OK (limited testing). This is not for the faint of heart. Rcp may be a good idea, regular ftp may be so too... The pre with ftp is that the other end is readily available, r-commands are sort of a forgotten species for security reasons.
> You mentioned that "hd -r" doesn't always work, can you explain in more detail where the bug is?
> 
Need more testing on this one. Try it locally on elks both ways, had trouble with that yesterday, then pursued other problems instead.

--M

**Comment by Mellvik** [comment]
I've updated the file transfer doc - it's more complete and cover transfer both ways. At some point it may be good to move it to the wiki.

--mellvik
