### ISSUE TITLE
[eth] Document more Ethernet

### ISSUE THREAD

**Issue by mfld-fr** [ghaerr/elks#79]
Following Derek's problem report on the mailing list (http://www.spinics.net/lists/linux-8086/msg00770.html), document more the Ethernet stuff in the existing "ELKS networking" document.

**Comment by georgp24** [comment]
Derek wrote: "sudo ./qemu.sh". It never works for me to run qemu.sh with sudo. 

Maybe you can discuss this in the qemu.html file.

**Comment by mfld-fr** [comment]
Oh really ? Starting `qemu.sh` works well with `sudo` on my side, and I wonder why you cannot run the emulator as `root`, the most privileged user ?

One should notice that, if QEMU runs with the help of KVM, you should add yourself to the `kvm` group if you want to run it as a normal user. But this does not explain the problem you mentioned.

**Comment by jbruchon** [comment]
I actually have this in my `/etc/rc` because /dev/kvm default permissions are `root:root` and `0600` and the KVM module doesn't auto-load:
```
modprobe kvm_amd
test -e /dev/kvm && chmod 660 /dev/kvm && chgrp kvm /dev/kvm
```
I'm not endorsing this as the solution, just showing what I've done to make sure the `kvm` group thing actually works as expected.

**Comment by mfld-fr** [comment]
Back to Derek's misuse : Georg has now documented how to select the right kernel option in the new `networking_guide.txt` documentation file (see jbruchon#82), and I think he fulfilled that way the need stated by this issue.
