### ISSUE TITLE
Network over httpS

### ISSUE THREAD

**Issue by toncho11** [ghaerr/elks#808]
Hi,

https://github.com/ARMmbed/mbedtls

I just wanted to point to this library. Maybe it will allow for console browsers and console rss readers to load HTTPS sites?

**Comment by ghaerr** [comment]
Hello @toncho11,

Thanks for pointing out the TLS library for embedded systems. I took a quick look at it: although it is billed as "small", it is only small by OpenSSL standards - but still huge. It requires a 32-bit CPU, so unfortunately will not be usable by ELKS.

Thank you!
