### ISSUE TITLE
nxworld improvements

### ISSUE THREAD

**Issue by toncho11** [ghaerr/elks#863]
1) If the map is not there we do not see the error message. It clears the screen when exiting, so it was a pure guess that the file was not there.

2) the file is searched only in /lib, it will better to search also the current folder. Seems natural.

3) the file is used as  "nxworld.map" at runtime, but it resides as "world.map" in git. So even after I copied the file in /lib it still did not work. So I had to also notice the name difference. 

4) The documentation says redraw map from top is "t", but in the code it is "r".

All these problems can happen to someone else and you need to look into the code to figure it out.
And mouse is extremely slow on 8 Mhz 8086.

**Comment by ghaerr** [comment]
Thanks @toncho11, I'll look into fixing these. Not sure before or after v0.4.0 though.

**Comment by pawosm-arm** [comment]
The map must have been drawn back in the 80s. Things have changed east to Poland since then...

**Comment by ghaerr** [comment]
@toncho11: I've fixed everything in PR #869 except for searching the current folder. If the map file is missing, it will display a message. Searching the current folder really isn't needed and is too much extra logic the way nxworld is written.

Thank you!

**Comment by toncho11** [comment]
#define	F_OK	0		/* Test for existence.  */

Thanks.

**Comment by ghaerr** [comment]
Thanks @toncho11, I'll get that F_OK added in another commit.
