### ISSUE TITLE
Boots DOS Svarog86 also

### ISSUE THREAD

**Issue by toncho11** [ghaerr/elks#864]
I have ELSK on /hda1 and DOS Svarog86 on /hda3. Svarog86 FreeDOS supports both fat16 and fat32. 

Both of them boot now!!!!!!!!!!!!!!!!!!!
I choose which one in ELKS boot manager (1 or 3).

There was some confusion with partition types etc, so what worked is formatting with Windows 10 as fat32 and then you need to use Svarog86 sys like that: format e: /S. Then partition type is reported "e" for "Win9x fat16 (LBA)" by fdisk and it is indeed fat16 changed by Svarog86 format command.

For Svarog86 I have to just say that command.com is on 3rd partition and it loads completely.

Wow. That is great. And I can exchange files between these.

I think we should document that it is possible to boot both.

**Comment by toncho11** [comment]
Dos 6.20 does not see the fat16 drive on which Svarog86 is installed.

**Comment by ghaerr** [comment]
> I think we should document that it is possible to boot both.

You're welcome to create another page on our Wiki and describe how one goes about creating partitions, loading other OS's, that sort of thing.

> Dos 6.20 does not see the fat16 drive on which Svarog86 is installed.

Has it ever before? How was the partition table created, some OS's are much more sensitive to the partition ID type set in the partition table. Fdisk will allow setting one of many partition types when creating, I don't think afterwards though.

I'm glad to hear that the ELKS MBR boots other OS's, that hadn't been previously tested.

**Comment by toncho11** [comment]
I added a wiki page Dual-boot-ELSK-and-DOS explaining this.

**Comment by ghaerr** [comment]
> I added a wiki page Dual-boot-ELSK-and-DOS explaining this.

Thanks! Can you fix the "ELSK" typo?
