### ISSUE TITLE
Enable pseudo ttys - pty

### ISSUE THREAD

**Issue by georgp24** [ghaerr/elks#88]
"make menuconfig" enables pseudo ttys as default. The pty.c driver is compiled too.

 However there are no ptys in the /dev directory and the MAKEDEV script states:
 "# Pseudo-TTY master devices. These are not yet supported by the ELKS kernel."

Can ptys be enabled in the MAKEDEV script or do they not work at all? The code says they were implemented for nano-X.

I would like to port a telnet server and need a pty for that.

**Comment by mfld-fr** [comment]
Tested with new `ptyshell` : OK
Issue fixed by eb352f3edf40f94bde8f2eb33a1ed1939c22736a (see jbruchon#92).
Should be closed.
