### ISSUE TITLE
diff not working

### ISSUE THREAD

**Issue by Mellvik** [ghaerr/elks#918]
The `diff` command reports `out of memory` regardless of input files.  sing `chmem` to manipulate heap and stack size does not seem to help.

```
# !23:p                                                                         
chmem -h 2048 ./diff                                                            
# ^2048^10240                                                                   
chmem -h 10240 ./diff                                                           
 TEXT  FTEXT   DATA    BSS   HEAP  STACK  TOTDATA  TOTAL                        
14736      0   1360   4384   2048      0    11888  26624 ./diff                 
14736      0   1360   4384  10240      0    20080  34816 ./diff                 
# !19                                                                           
./diff /root/file /root/file2                                                   
sys_brk(35) fail: brk 2a70 over by 1010 bytes                                   
sys_brk(35) fail: brk 2872 over by 500 bytes                                    
./diff: out of memory                                                           
# chmem -s 2048 ./diff                                                          
 TEXT  FTEXT   DATA    BSS   HEAP  STACK  TOTDATA  TOTAL                        
14736      0   1360   4384  10240      0    20080  34816 ./diff                 
14736      0   1360   4384  10240   2048    18032  32768 ./diff                 
# !19                                                                           
./diff /root/file /root/file2                                                   
sys_brk(37) fail: brk 2a70 over by 1010 bytes                                   
sys_brk(37) fail: brk 2872 over by 500 bytes                                    
./diff: out of memory                                                           
# 
```

What am I missing?

--M

**Comment by ghaerr** [comment]
Hello @Mellvik,

You're doing the right thing by increasing the heap, except probably by not enough. Try specifying "max heap" using the following:
```
# chmem -h 0xffff /bin/diff
```
Passing `-h 0xffff` (64k - 1 = 65535) tells the kernel to allocate 64k for the data segment. The heap size will be the remainder of the data segment less the DATA, BSS and stack regions (in this case, 64k - 1360 - 4384 - 4k). Without the "max heap" specification, the system will allocate a data segment that allows for a 4K heap (which would be 1360 + 4384 + 4K stack + 4K heap).

It is not recommended to change the default stack size (using -s), which is 4K, without looking at the source code for stack-based buffers. The default stack of 4K is allocated at the end of the data segment.

If we find that the above allows diff to run, then a PR can be created adding the `-maout-heap=0xffff` option to the diff Makefile.

Thank you!

**Comment by Mellvik** [comment]
Thanks @ghaerr,

the 64k heap setting did the trick.

I'll include it in a PR.


—M
