### ISSUE TITLE
Question: EEPROM/Flash update app (xmodem/zmodem)

### ISSUE THREAD

**Issue by cocus** [ghaerr/elks#983]
I don't know if there's already tool that runs on RAM and allows the user to flash the "bios" (in this case it would be where the actual elks kernel + filesystem resides) via xmodem/zmodem or any of these file transfer protocols.
My reasoning comes from the idea that it's not fun to take the flash chip every time I need to test a hardware-related change. I would rather sideload it from the UART or even from the SD card (assuming the application has full control of the SD card, and disregards any elks-related code).
If nothing like this exists, I think the first thing would be to validate that an app does actually run from RAM instead of ROM. Then, make it NOT use any elks related APIs (like ioctls and such), disable interrupts and interact with the UART directly. I guess this should be doable, right?

Thanks

**Comment by ghaerr** [comment]
Hello @cocus, 

I'm not fully following you; are you saying you'd like to have an ELKS application that would read a file using, say, xmodem or ymodem, then have that same application flash that file as the running system's BIOS?

If so, I would suggest that a seperate xmodem/ymodem application be written, using the standard Linux system calls (open, read/write, etc), and specify the output file be on a mounted RAM disk on the system. This gets the BIOS image over into the running ROMFS/RAMFS system, and could be tested on the desktop. Then, a seperate program could read that file (or ROMFS file for backup if wanted) and flash that file as the running system BIOS. The way that could work would be that it would also be a normal ELKS application, (that reads a file specified from the RAMFS) into a malloced area of memory. Then, after everything is in memory, it would call a procedure that effectively turns off interrupts and performs the flash using hardware directly, with the kernel basically turned off. After that, it could either reboot the system, or enable interrupts and carry on normally and exit back to ELKS. If one was careful, the only system interrupts that would be missed during a hard interrupts off would be the timer interrupt, which wouldn't really hurt anything.

The entire process could be assigned an alias in the `sash` shell, for mounting the RAM filesystem, doing the xmodem, then doing the flash.

Thank you!

**Comment by ghaerr** [comment]
If the second application were designed to be passed a memory address along with a binary image, then it could be setup to flash either a new kernel, a new ROMFS filesystem, or both. Seperate images could be transferred beforehand with the xmodem application, then flashed as desired. That would be cool!

You can look at `miniterm` to see an example of how to access the serial port using standard Linux functions. There's probably a number of tiny xmodem applications out there for Linux that could be easily ported using the information from `miniterm`.

**Comment by cocus** [comment]
> I'm not fully following you; are you saying you'd like to have an ELKS application that would read a file using, say, xmodem or ymodem, then have that same application flash that file as the running system's BIOS?

Correct. Since my board doesn't have a BIOS, it has to update the entire flash (ROM) where ELKS is currently running from. This is not "nice" as you can see, but my idea is to make this app to be loaded on RAM, then take over the entire CPU and UART so it doesn't use ANY API from elks (like the unix stuff); this way I could technically update the flash and then reboot the CPU.


> If so, I would suggest that a seperate xmodem/ymodem application be written, using the standard Linux system calls (open, read/write, etc), and specify the output file be on a mounted RAM disk on the system. This gets the BIOS image over into the running ROMFS/RAMFS system, and could be tested on the desktop. Then, a seperate program could read that file (or ROMFS file for backup if wanted) and flash that file as the running system BIOS. The way that could work would be that it would also be a normal ELKS application, (that reads a file specified from the RAMFS) into a malloced area of memory. Then, after everything is in memory, it would call a procedure that effectively turns off interrupts and performs the flash using hardware directly, with the kernel basically turned off. After that, it could either reboot the system, or enable interrupts and carry on normally and exit back to ELKS. If one was careful, the only system interrupts that would be missed during a hard interrupts off would be the timer interrupt, which wouldn't really hurt anything.

Right, that'll make a lot of sense to do, *however* my board doesn't have enough RAM to hold the entire image I'm trying to update. (i.e. I have both 512k parts). Hence the need to NOT use any elks system calls while doing this.

> If the second application were designed to be passed a memory address along with a binary image, then it could be setup to flash either a new kernel, a new ROMFS filesystem, or both. Seperate images could be transferred beforehand with the xmodem application, then flashed as desired. That would be cool!

Ah, this is a nicer approach than my "update the entire FLASH in one go" idea. Let's use my board as an example. I have 512k of RAM. The romfs is size-limited as you've told me before (don't remember the exact value, but it has a limit), and the elks kernel can't be bigger than 512k anyway, right? In this scenario, if I want to malloc() an entire region of RAM to hold the romfs, would it even fit? If the romfs is 256k (random figure), would I have enough space to do such malloc? Same would apply to the elks kernel.

Afterwards, I would receive the binary via xmodem or whatever (using unix calls and all these nice things we have), then turn off interrupts, update flash & reboot.



> You can look at `miniterm` to see an example of how to access the serial port using standard Linux functions. There's probably a number of tiny xmodem applications out there for Linux that could be easily ported using the information from `miniterm`.

Right, I would do so after I figure out which way to do this kind of update.

**Comment by ghaerr** [comment]
> In this scenario, if I want to malloc() an entire region of RAM to hold the romfs, would it even fit? If the romfs is 256k (random figure), would I have enough space to do such malloc?

Well, `malloc` won't work, as the max allocation actually is 32767 bytes (with some kluges could go to just under 64K). We can surely figure out a way to determine a way to get a pointer to where some free memory is. I'm still thinking perhaps we build a system that allows for a variable-sized, or RAM disk created only after boot, and then after transferring a file using xmodem to that memory, we use an `ioctl` to the RAM disk to get a far pointer to the memory the file resides in. This is a bit tricky, as it would be a Minix filesystem, but we could guarantee consecutive sectors if it was freshly mkfs'd. The RAMFS filesystem doesn't really use much extra memory...

Exactly how big do each of the binary images need to be? We can work from there to determine how to do this. I'm always for using applications to use existing services rather than writing stuff directly to hardware, which keeps things much easier to port later on, which it seems always needs to be done.

**Comment by cocus** [comment]
> Exactly how big do each of the binary images need to be? We can work from there to determine how to do this. I'm always for using applications to use existing services rather than writing stuff directly to hardware, which keeps things much easier to port later on, which it seems always needs to be done.

Well, both images produces by ELKS are going to be updated on the FLASH (Image + romfs).


I'm having some issues trying to even read the flash jedec device ID with a simple program, have a look:
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdint.h>
#include <string.h>
#include "arch/io.h"

#define irq_disable(_x) \
	asm volatile ("cli": : :"memory")

#define irq_enable(_x) \
	asm volatile ("sti": : :"memory")

#define clr_irq irq_disable
#define set_irq irq_enable

static inline void writeb(unsigned short segment,
                          unsigned short address,
                          unsigned char val)
{
    asm volatile(
        "push %%ds\n"
        "mov %P[segment], %%ds\n"
        "mov %P[address], %%bx\n"
        "movb %P[val], (%%bx)\n"
        "pop %%ds"
        :
        : [segment] "r"(segment), [address] "m"(address), [val] "r"(val)
        : "%bx", "memory");
}

static inline void writew(unsigned short segment,
                          unsigned short address,
                          unsigned short val)
{
    asm volatile(
        "push %%ds\n"
        "mov %P[segment], %%ds\n"
        "mov %P[address], %%bx\n"
        "movw %P[val], (%%bx)\n"
        "pop %%ds"
        :
        : [segment] "r"(segment), [address] "m"(address), [val] "r"(val)
        : "%bx", "memory");
}

static inline unsigned char readb(unsigned short segment,
                                  unsigned short address)
{
    unsigned char v;

    asm volatile(
        "push %%ds\n"
        "mov %P[segment], %%ds\n"
        "mov %P[address], %%bx\n"
        "movb (%%bx), %P[val]\n"
        "pop %%ds"
        : [val] "=r"(v)
        : [segment] "r"(segment), [address] "m"(address)
        : "%bx", "memory");

    return v;
}

static inline unsigned short readw(unsigned short segment,
                                   unsigned short address)
{
    unsigned short v;

    asm volatile(
        "push %%ds\n"
        "mov %P[segment], %%ds\n"
        "mov %P[address], %%bx\n"
        "movw (%%bx), %P[val]\n"
        "pop %%ds"
        : [val] "=r"(v)
        : [segment] "r"(segment), [address] "m"(address)
        : "%bx", "memory");

    return v;
}

static inline unsigned short get_cs(void)
{
    unsigned short cs;

    asm volatile("mov %%cs, %0" : "=r"(cs));

    return cs;
}

int main (int argc, char **argv)
{
    uint8_t manuf, devcode, sectst;

    printf("killing IRQs...\n");

    sleep(1);

    clr_irq();

    //internal_puts("In control, continuing\n");

    //internal_puts("CS: 0x"); serial_hexnum16(get_cs()); cout('\n');

    //internal_puts("resetting flash\n");
    writeb(0x800, 0x000, 0xf0);
    //internal_puts("autoselect");
    writeb(0x800, 0x0555, 0xaa);
    writeb(0x800, 0x02aa, 0x55);
    writeb(0x800, 0x0555, 0x90);
    manuf = readb(0x800, 0x0000);
    devcode = readb(0x800, 0x0001);
    sectst = readb(0x800, 0x0002);
    //internal_puts("resetting flash\n");
    writeb(0x800, 0x000, 0xf0);

    set_irq();

    printf("welp, manuf=0x%.4x, devcode=0x%.4x, sectst=0x%.4x\n", manuf, devcode, sectst);

    return 0;
}
```

Per the datasheet of my flash memory (MBM29F040C): 
![image](https://user-images.githubusercontent.com/523726/140588330-29e17e7b-1c64-46fc-aa2a-9ac46b455db3.png)

```
The device contains an Autoselect command operation to supplement traditional PROM programming methodology. The operation is initiated by writing the Autoselect command sequence into the command register. Following the command write, a read cycle from address XX00H retrieves the manufacture code of 04H. A read cycle from address XX01H returns the device code A4H. 
```

But I always get wrong values:
```
killing IRQs...
welp, manuf=0xf0, devcode=0x0, sectst=0x0
```

Not sure if my assembly routines to write and read bytes are wrong or not. Worst case scenario, my code might not be running from RAM? (I'm running it from the mounted SD card)

**Comment by ghaerr** [comment]
> Not sure if my assembly routines to write and read bytes are wrong or not.

I'm the wrong guy to ask when it comes to gcc's complex `asm` code. I suggest using `ia16-elf-objdump -D -r -Mi8086` on the .o file and inspecting the code produced for the readb/writeb routines and see if it's what you wanted.
We can reach out to tkchia if you need more help on the gcc asm workings.

> Worst case scenario, my code might not be running from RAM? (I'm running it from the mounted SD card)

No - the kernel reads in the file header and executable contents from the [mounted SD card,romfs,minix,fat] filesystem into RAM in every case.

**Comment by cocus** [comment]
I would like to summon @tkchia if possible, since I don't want to pull the flash chip anymore from the board. I would rather run a simple kermit-like or {x,y,z}-modem protocol to update my flash.


> I'm the wrong guy to ask when it comes to gcc's complex `asm` code. I suggest using `ia16-elf-objdump -D -r -Mi8086` on the .o file and inspecting the code produced for the readb/writeb routines and see if it's what you wanted.

Since they were marked as inline, I don't fully see them as-is. Not sure if it's because of the fact they're inline, or if something went south.
As I saw, __FAR is declared so my code was using the following snippets for read/write bytes or words:
```
static inline void writeb(unsigned short segment,
                          unsigned short address,
                          unsigned char val)
{
    unsigned char volatile __far *fp = (unsigned char volatile __far *)
        ((unsigned long)segment << 16 | address);
    *fp = val;
}

static inline void writew(unsigned short segment,
                          unsigned short address,
                          unsigned short val)
{
    unsigned short volatile __far *fp = (unsigned short volatile __far *)
        ((unsigned long)segment << 16 | address);
    *fp = val;
}

static inline unsigned char readb(unsigned short segment,
                                  unsigned short address)
{
    unsigned char volatile __far *fp = (unsigned char volatile __far *)
        ((unsigned long)segment << 16 | address);
    return *fp;
}

static inline unsigned short readw(unsigned short segment,
                                   unsigned short address)
{
    unsigned short volatile __far *fp = (unsigned short volatile __far *)
        ((unsigned long)segment << 16 | address);
    return *fp;
}
```

These came from https://github.com/jamieiles/80x86. Do you think they have an issue?

Also, what would be a good tradeoff that doesn't require these helper functions to just use __far from gcc? I assume something like what elks uses on multiple places might do the trick. Can you suggest a good example of __far?




> No - the kernel reads in the file header and executable contents from the [mounted SD card,romfs,minix,fat] filesystem into RAM in every case.

Ok good, so disabling the IRQs would mean my code won't be bothered by anything and I can take over the serial port without using IRQs and read/write to the FLASH without issues.

**Comment by tkchia** [comment]
Hello @cocus,

> Since they were marked as inline, I don't fully see them as-is. Not sure if it's because of the fact they're inline, or if something went south.

Look for the code in the compiled `main` function that does the I/O.  Anyway, this is what I am getting (with an optimization setting of `-Os`):
```
   9:   bf 01 00                mov    $0x1,%di
   c:   57                      push   %di
   d:   e8 fe ff                call   e <main+0xe>
                        e: R_386_PC16   sleep
  10:   fa                      cli    
  11:   31 f6                   xor    %si,%si
  13:   b8 00 08                mov    $0x800,%ax
  16:   8e d8                   mov    %ax,%ds
  18:   c6 04 f0                movb   $0xf0,(%si)
  1b:   bb 55 05                mov    $0x555,%bx
  1e:   c6 07 aa                movb   $0xaa,(%bx)
  21:   c6 06 aa 02 55          movb   $0x55,0x2aa
  26:   c6 07 90                movb   $0x90,(%bx)
  29:   8a 14                   mov    (%si),%dl
  2b:   8a 35                   mov    (%di),%dh
  2d:   8a 0e 02 00             mov    0x2,%cl
  31:   c6 04 f0                movb   $0xf0,(%si)
  34:   fb                      sti    
```

This does seem to agree with your code above.

But... the segment value of `0x800` looks kind of low to me.  Are you sure that it is correct?  `0x800:0` will only be at `0x8000` bytes &mdash; or 32 KiB &mdash; into your machine's physical address space.  Do you actually intend to access some other addresses?

Thank you!

**Comment by cocus** [comment]
> But... the segment value of `0x800` looks kind of low to me. Are you sure that it is correct? `0x800:0` will only be at `0x8000` bytes — or 32 KiB — into your machine's physical address space. Do you actually intend to access some other addresses?

OH, I think I forgot a zero! Yes, the flash is right in the middle of the address space, so it should be at 0x80000, so the segment value should be 0x8000! Doh!!!! 

In any case, how can I access these memory locations directly without resorting to these inline functions? I don't want to use any OS related functions either (since I want this to run fully on RAM almost like a stand-alone baremetal app).

Thank you for your quick response!

**Comment by ghaerr** [comment]
> In any case, how can I access these memory locations directly without resorting to these inline functions? 

You could use something like the following, where `addr32` is an unsigned long "physical linear address". The compiler will generate fast code using an ES or DS override to access the value at the passed address:
```
#include <memory.h>

#define LINEAR(addr32)  _MK_FP(addr32 >> 4, addr32 & 0x0F)

unsigned long addr = 0x81234; /* linear address to access */
char __far *p = LINEAR(addr);  /* same far address to directly access with compiler code ES: or DS: override */

if (*p == WHATEVER) *p = SOMETHING;  // etc
```

**Comment by tkchia** [comment]
Hello @ghaerr,

> ```
> char __far *p = LINEAR(addr);
> ```

Indeed, that should work &mdash; though for memory-mapped devices (like what we are discussing) we probably want to have a pointer to a `volatile`, e.g.

> ```
> volatile char __far *p = LINEAR(addr);
> ```

Hello @cocus,

> Yes, the flash is right in the middle of the address space, so it should be at 0x80000, so the segment value should be 0x8000!

Cool, glad the problem has been identified. :slightly_smiling_face: 

> In any case, how can I access these memory locations directly without resorting to these inline functions?

Well, the inline functions _do_ result in code that is quite efficient, as you can see from the `ia16-elf-objdump` dump above.

But if you want more flexibility in how you manipulate these far addresses: basically, you can create a far pointer by
  * casting a 32-bit integer to some `__far *` type &mdash; the high 16 bits will be the segment, and the low 16 bits the offset &mdash; or
  * casting a good old near pointer (e.g. `void *`) to a `__far *` type &mdash; this will create a pointer that points to the same effective address as the original near pointer.

And yes... that is basically it.  Once you create a far pointer, you can do many of the usual things with it that you do with "normal" pointers: dereference them (unless `void`), pass them as parameters to functions, store them in arrays or structures, etc.  And, just like "normal" pointers, they can point to either `const` or non-`const` things, either `volatile` or non-`volatile` things, etc.

(The `_MK_FP` macro in `<memory.h>` (or, for other platforms, `<i86.h>`) is simply some syntactic sugar for creating a 32-bit integer and then turning it into a far pointer.)

Thank you!

**Comment by cocus** [comment]
Thanks for the amazing feedback @ghaerr and @tkchia ! I can talk to the Flash memory (or at least I can read the device id) properly:
```
Fri Jan 21 00:05:31 2022
CS: 0x2255
resetting flash
 done, manuf=0x4, devcode=0xa4, sectst=0x0
resetting flash
```
That matches the datasheet `Byte 0 (A0 = VIL) represents the manufacture’s code (Fujitsu = 04H) and byte 1 (A0 = VIH) represents the device identifier code (MBM29F040C = A4H).`
I'll have to dive deep in order to figure out how to do this properly, writing flash memory is not funny!

This is my code:
```

int main (int argc, char **argv)
{
    uint8_t manuf, devcode, sectst;

    volatile char __far *flash_at80000 = LINEAR(0x80000);
    volatile char __far *flash_at80001 = LINEAR(0x80001);
    volatile char __far *flash_at80002 = LINEAR(0x80002);
    volatile char __far *flash_at80555 = LINEAR(0x80555);
    volatile char __far *flash_at802aa = LINEAR(0x802aa);

    printf("%s\n", __TIMESTAMP__);

    *flash_at80000 = 0xf0;
    *flash_at80555 = 0xaa;
    *flash_at802aa = 0x55;
    *flash_at80555 = 0x90;

    manuf = *flash_at80000;
    devcode = *flash_at80001;
    sectst = *flash_at80002;
    *flash_at80000 = 0xf0;

    printf("manuf=0x%x, devcode=0x%x, sectst=0x%x\n", manuf, devcode, sectst);
    
    return 0;
}
```
And I checked the output of the objdump, and the assembly is so optimized that I couldn't even believe it. Great job!

I'll mark this as resolved in a short while, maybe I can share my flash tool if it ends up being useful for someone else!

Thanks!
