### ISSUE TITLE
KTCP ignoring peer's closing window

### ISSUE THREAD

**Issue by Mellvik** [ghaerr/elks#986]
Summary:
When sending data, `ktcp` seems to (at least partly) ignore a peer's closing window.

Here's what seems to be going on:
- Elks is happily sending data to the recipient (ftpput), 512b payload per packet, receiving ACKs for every 2 or 3 packet.
- The recipient is a raspberrypi, very fast compared to the ELKS machine (386/20), with a floppy disk (USB) for the occasion, to slow down the transfer and cause write errors.
- When the recipient suddenly needs ELKS to slow down, it reduces its window to 512 (from 2048 or larger in the preceding packets).
- Elks seemingly reponds to this by reducing the next packet payload to 360.
- At this point - until the recipient has told ELKS otherwise, the actual window is 512-360=152b.
- But ELKS doesn't wait. Immediately after the 360 size packet, comes another series of 512 byte packets, which the recipient is now unable to process.
- At this point, after 4 512-byte packets, the recipient desperately sends an empty ACK back to ELKS advertizing a ZERO window and repeating the previous ACK, not acknowledging any of the last 4 packets.

There are other observations to be made from the following packets, but it's probably not interesting if the problem is that `ktcp` fails to recognize that the recipient window has closed.

Any suggestions, @ghaerr?

--Mellvik

**Comment by ghaerr** [comment]
I seem to remember that `ktcp` may not stop sending packets based on the received window size at all, which sounds like what is happening. I'll look at the code and respond with what `ktcp` actually is coded for and respond. 

In summary, ELKS TCP is now receiving quite well, and with some minor tweaks can improve that speed with some possibly dynamically specified broadcast window size, but now you've found that sending data from ELKS is problematic, as described above, correct?

In this non-stop sending, do the systems ever return to sync, or does the outgoing transfer finally fail?

**Comment by Mellvik** [comment]
@ghaerr,
Now that you mention it - I do recall we've touched that one before.
Maybe this is a good time to revisit, now that the receving is under control.

> In this non-stop sending, do the systems ever return to sync, or does the outgoing transfer finally fail?

Eventually ktcp realizes the missing ACKs and starts repeating the last packet. And eventually the recipient reopens the window, without ACKing any of the un-ack'ed packets. KTCP keeps resending the last packet, the recipient closes the window again and so on. Finally ktcp just goes quiet and hangs hard. See the netstat from the previous post. 
Ktcp is still operational though, telnet in and out works.

More details on this tomorrow.

--M

**Comment by ghaerr** [comment]
> I seem to remember that ktcp may not stop sending packets based on the received window size at all

Actually, `ktcp` was fixed last year to limit sending packets by comparing the amount of previous data sent from the last acknowledged sequence number (the outstanding send window). But it appears this is compared against a fixed value of 1024, instead of the remote peer's receive window. 

I'll prepare a PR that hopefully should fix this issue, as well as advertising a larger receive window (configurable at 640 for the time being) that speeds up file transfers considerably, discussed in https://github.com/jbruchon/elks/issues/976#issuecomment-953244002.

**Comment by Mellvik** [comment]
OK @ghaerr, that makes sense.

It seems we have two - possibly related - problems or bugs at work here.
One is the failure to act on a shrinking peer window,
the other is the failure to go back to the first unacknowledged packet.

Anyway - it seems we're getting there.


Thank you.

—Mellvik
