### ISSUE TITLE
Error Building with cgatext enabled

### ISSUE THREAD

**Issue by SonnoOcea** [ghaerr/elks#991]
I can't compile ELKS with 'cgatext' enabled.

I get this error (not complete log, if needed I can make a pastebin)
```
main.c:191:8: note: in expansion of macro ‘cgatext_color_GREEN’
        cgatext_color_GREEN | cgatext_attr_BOLD,
        ^~~~~~~~~~~~~~~~~~~
make[4]: *** No rule to make target '../../elks/arch/i86/lib//libmem.a', needed by 'cgatext'.  Stop.
make[4]: Leaving directory '/home/sonno/elks/elkscmd/cgatext'
make[3]: *** [Make.install:159: install] Error 2
make[3]: Leaving directory '/home/sonno/elks/elkscmd'
make[2]: *** [Make.image:49: template] Error 2
make[2]: Leaving directory '/home/sonno/elks/image'
make[1]: *** [Makefile:28: image] Error 2
make[1]: Leaving directory '/home/sonno/elks/image'
make: *** [Makefile:16: all] Error 2
```
I'm compiling on a VM with Debian11 on it, with the latest commit re-cloned this evening just to be sure.

To reproduce this:
I cloned the repo,
moved into it,
mkdir cross
tools/build.sh
. ./env.sh
make menuconfig
enabled unix sockets, chron, busyelks and cgatext,
make all

It does this every time on this VM, I have yet to reproduce this on another machine, mainly due to having some different errors when compiling the toolchain on my main.

It does build succesfully if I don't enable cgatext.

Sorry for sending an uncomplete issue, but I erronously hit shift+enter,
Have a good evening

**Comment by ghaerr** [comment]
Hello @SonnoOcea,

Thanks for the bug report.

The problem is in the file 'elkscmd/cgatext/makefile'. Change the LIBS= line in that file to the following and cgatext should compile:
```
LIBS   = $(ELKS_LIB86)/lib86.a
```
I'll get this fixed in an upcoming PR.

Thank you!

**Comment by SonnoOcea** [comment]
Thanks a lot ghaerr!
The edit did indeed work and I had a succesful build,
I'll check later if it works or not on the hardware itself and I'll let you know and close the issue.

**Comment by SonnoOcea** [comment]
I tested it on a pentium (overkill, but the v20 xt clone I want to use it on needs maintenance) and **it does work correctly** indeed, thanks again for the help.

For future reference the images built can be used with a gotek by just renaming the file the bin to img (both formats are raw images of floppy disks).

Have a nice day!

![photo_2021-11-09_12-31-26](https://user-images.githubusercontent.com/22325420/140917022-671d91c6-0cc3-40d3-8fcc-460d083550cc.jpg)
![photo_2021-11-09_12-31-33](https://user-images.githubusercontent.com/22325420/140917073-40d95df2-f405-4fba-8f25-a0b32ea3fb07.jpg)
